/********************************************************************************
** Form generated from reading UI file 'Boss-rc500XKRPpk.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef BOSS_2D_RC500XKRPPK_H
#define BOSS_2D_RC500XKRPPK_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>

QT_BEGIN_NAMESPACE

class Ui_BossRc500Dialog
{
public:
    QLabel *label_File;
    QPushButton *button_Open;
    QLabel *label_LoopStation;
    QPushButton *button_Save;
    QLabel *label_To;
    QPushButton *button_Quit;
    QComboBox *cb_CopyFrom;
    QLabel *label_Memory;
    QComboBox *cb_Memory;
    QLabel *label_CopyTo;
    QLabel *label_Filename;
    QLabel *label_Boss;
    QComboBox *cb_CopyTo;
    QGroupBox *gp_Track1;
    QCheckBox *track1_Reverse;
    QSlider *track1_Level;
    QLabel *label_track1_Level;
    QCheckBox *track1_LoopFx;
    QCheckBox *track1_OneShot;
    QLabel *label_track1_Pan;
    QComboBox *track1_Pan;
    QComboBox *track1_Stop;
    QLabel *label_track1_Stop;
    QComboBox *track1_Start;
    QLabel *label_track1_Start;
    QComboBox *track1_Measure;
    QLabel *label_track1_Measure;
    QCheckBox *track1_LoopSync;
    QCheckBox *track1_TempoSync;
    QLabel *label_track1_Output;
    QComboBox *track1_Input;
    QComboBox *track1_Output;
    QLabel *label_track1_Input;
    QLabel *label_track1_PlyLevel;
    QGroupBox *gp_Track2;
    QComboBox *track2_Measure;
    QLabel *label_track2_Stop;
    QLabel *label_track2_Output;
    QComboBox *track2_Stop;
    QComboBox *track2_Pan;
    QCheckBox *track2_OneShot;
    QCheckBox *track2_TempoSync;
    QCheckBox *track2_LoopSync;
    QLabel *label_track2_Measure;
    QComboBox *track2_Output;
    QLabel *label_track2_Start;
    QLabel *label_track2_Input;
    QCheckBox *track2_Reverse;
    QComboBox *track2_Start;
    QComboBox *track2_Input;
    QCheckBox *track2_LoopFx;
    QSlider *track2_Level;
    QLabel *label_track2_Level;
    QLabel *label_track2_Pan;
    QLabel *label_track2_PlyLevel;
    QPushButton *button_Copy;
    QGroupBox *gp_Record;
    QLabel *label_record_DubMode;
    QComboBox *record_DubMode;
    QComboBox *record_Quantize;
    QLabel *label_record_Quantize;
    QComboBox *record_RecordAction;
    QLabel *label_record_RecordAction;
    QCheckBox *record_AutoRecord;
    QLabel *label_record_AutoRecordSource;
    QComboBox *record_AutoRecordSource;
    QLabel *label_record_Input_3;
    QLabel *label_record_LoopLength;
    QComboBox *record_LoopLength;
    QSpinBox *record_AutoRecordSensitivity;
    QGroupBox *gp_Play;
    QLabel *label_play_PlayMode;
    QComboBox *play_PlayMode;
    QLabel *label_play_Level;
    QComboBox *play_SingleChange;
    QLabel *label_play_SingleChange;
    QLabel *label_play_AllStart;
    QComboBox *play_FadeTime;
    QComboBox *play_AllStart;
    QLabel *label_play_FadeTime;
    QLabel *label_play_TrackChain;
    QComboBox *play_TrackChain;
    QSpinBox *play_Level;
    QGroupBox *gp_Rhythm;
    QSlider *rhythm_level;
    QLabel *label_track1_Level_2;
    QLabel *label_track1_Level_3;
    QSlider *rhythm_reverb;
    QComboBox *track1_Start_2;
    QLabel *label_track1_Start_2;
    QComboBox *track1_Start_3;
    QLabel *label_track1_Start_3;
    QComboBox *track1_Start_4;
    QLabel *label_track1_Start_4;
    QLabel *label_track1_Start_5;
    QComboBox *track1_Start_5;
    QLabel *label_track1_Start_6;
    QComboBox *track1_Start_6;
    QLabel *label_track1_Start_7;
    QComboBox *track1_Start_7;
    QLabel *label_track1_Start_8;
    QComboBox *track1_Start_8;
    QComboBox *track1_Start_9;
    QLabel *label_track1_Start_9;
    QLabel *label_track1_Start_10;
    QComboBox *track1_Start_10;
    QCheckBox *track2_Reverse_2;
    QCheckBox *track2_Reverse_3;
    QCheckBox *track2_Reverse_4;
    QCheckBox *track2_Reverse_5;
    QCheckBox *track2_Reverse_6;
    QLabel *label_track1_Start_11;
    QLabel *label_track1_Start_12;
    QSlider *track1_Level_4;
    QSlider *track1_Level_5;
    QGroupBox *gb_LoopFx;
    QLabel *label_loopFx_Type;
    QComboBox *loopFx_Type;
    QLabel *label_loopFx_ScatLen;
    QComboBox *loopFx_ScatLen;
    QComboBox *loopFx_ReptLen;
    QLabel *label_loopFx_ReptLen;
    QLabel *label_loopFx_Shift;
    QComboBox *loopFx_Shift;
    QLabel *label_loopFx_Flick;
    QSpinBox *loopFx_Flick;
    QCheckBox *loopFx_Sw;

    void setupUi(QDialog *BossRc500Dialog)
    {
        if (BossRc500Dialog->objectName().isEmpty())
            BossRc500Dialog->setObjectName(QString::fromUtf8("BossRc500Dialog"));
        BossRc500Dialog->resize(1033, 711);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(170, 49, 45, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        BossRc500Dialog->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("Bitstream Vera Sans"));
        font.setBold(true);
        font.setWeight(QFont::DemiBold);
        BossRc500Dialog->setFont(font);
        label_File = new QLabel(BossRc500Dialog);
        label_File->setObjectName(QString::fromUtf8("label_File"));
        label_File->setGeometry(QRect(10, 50, 41, 21));
        button_Open = new QPushButton(BossRc500Dialog);
        button_Open->setObjectName(QString::fromUtf8("button_Open"));
        button_Open->setGeometry(QRect(50, 50, 51, 24));
        label_LoopStation = new QLabel(BossRc500Dialog);
        label_LoopStation->setObjectName(QString::fromUtf8("label_LoopStation"));
        label_LoopStation->setGeometry(QRect(690, 0, 341, 31));
        label_LoopStation->setPixmap(QPixmap(QString::fromUtf8("resources/images/loop station.png")));
        label_LoopStation->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        button_Save = new QPushButton(BossRc500Dialog);
        button_Save->setObjectName(QString::fromUtf8("button_Save"));
        button_Save->setGeometry(QRect(900, 50, 51, 24));
        label_To = new QLabel(BossRc500Dialog);
        label_To->setObjectName(QString::fromUtf8("label_To"));
        label_To->setGeometry(QRect(530, 50, 21, 21));
        button_Quit = new QPushButton(BossRc500Dialog);
        button_Quit->setObjectName(QString::fromUtf8("button_Quit"));
        button_Quit->setGeometry(QRect(970, 50, 51, 24));
        cb_CopyFrom = new QComboBox(BossRc500Dialog);
        cb_CopyFrom->setObjectName(QString::fromUtf8("cb_CopyFrom"));
        cb_CopyFrom->setGeometry(QRect(470, 50, 51, 25));
        label_Memory = new QLabel(BossRc500Dialog);
        label_Memory->setObjectName(QString::fromUtf8("label_Memory"));
        label_Memory->setGeometry(QRect(180, 50, 61, 21));
        cb_Memory = new QComboBox(BossRc500Dialog);
        cb_Memory->setObjectName(QString::fromUtf8("cb_Memory"));
        cb_Memory->setGeometry(QRect(250, 50, 91, 25));
        label_CopyTo = new QLabel(BossRc500Dialog);
        label_CopyTo->setObjectName(QString::fromUtf8("label_CopyTo"));
        label_CopyTo->setGeometry(QRect(420, 50, 41, 21));
        label_Filename = new QLabel(BossRc500Dialog);
        label_Filename->setObjectName(QString::fromUtf8("label_Filename"));
        label_Filename->setGeometry(QRect(10, 80, 1021, 21));
        label_Boss = new QLabel(BossRc500Dialog);
        label_Boss->setObjectName(QString::fromUtf8("label_Boss"));
        label_Boss->setGeometry(QRect(0, 0, 190, 40));
        label_Boss->setPixmap(QPixmap(QString::fromUtf8("resources/images/boss.png")));
        cb_CopyTo = new QComboBox(BossRc500Dialog);
        cb_CopyTo->setObjectName(QString::fromUtf8("cb_CopyTo"));
        cb_CopyTo->setGeometry(QRect(560, 50, 51, 25));
        gp_Track1 = new QGroupBox(BossRc500Dialog);
        gp_Track1->setObjectName(QString::fromUtf8("gp_Track1"));
        gp_Track1->setGeometry(QRect(10, 100, 301, 341));
        track1_Reverse = new QCheckBox(gp_Track1);
        track1_Reverse->setObjectName(QString::fromUtf8("track1_Reverse"));
        track1_Reverse->setGeometry(QRect(80, 30, 91, 23));
        track1_Reverse->setLayoutDirection(Qt::RightToLeft);
        track1_Level = new QSlider(gp_Track1);
        track1_Level->setObjectName(QString::fromUtf8("track1_Level"));
        track1_Level->setGeometry(QRect(10, 30, 41, 251));
        track1_Level->setMaximum(200);
        track1_Level->setOrientation(Qt::Vertical);
        track1_Level->setTickPosition(QSlider::TicksBothSides);
        label_track1_Level = new QLabel(gp_Track1);
        label_track1_Level->setObjectName(QString::fromUtf8("label_track1_Level"));
        label_track1_Level->setGeometry(QRect(10, 290, 41, 21));
        track1_LoopFx = new QCheckBox(gp_Track1);
        track1_LoopFx->setObjectName(QString::fromUtf8("track1_LoopFx"));
        track1_LoopFx->setGeometry(QRect(90, 50, 81, 23));
        track1_LoopFx->setLayoutDirection(Qt::RightToLeft);
        track1_LoopFx->setAutoFillBackground(false);
        track1_OneShot = new QCheckBox(gp_Track1);
        track1_OneShot->setObjectName(QString::fromUtf8("track1_OneShot"));
        track1_OneShot->setGeometry(QRect(80, 70, 91, 23));
        track1_OneShot->setLayoutDirection(Qt::RightToLeft);
        label_track1_Pan = new QLabel(gp_Track1);
        label_track1_Pan->setObjectName(QString::fromUtf8("label_track1_Pan"));
        label_track1_Pan->setGeometry(QRect(90, 100, 61, 21));
        track1_Pan = new QComboBox(gp_Track1);
        track1_Pan->setObjectName(QString::fromUtf8("track1_Pan"));
        track1_Pan->setGeometry(QRect(160, 100, 91, 25));
        track1_Stop = new QComboBox(gp_Track1);
        track1_Stop->setObjectName(QString::fromUtf8("track1_Stop"));
        track1_Stop->setGeometry(QRect(160, 160, 121, 25));
        label_track1_Stop = new QLabel(gp_Track1);
        label_track1_Stop->setObjectName(QString::fromUtf8("label_track1_Stop"));
        label_track1_Stop->setGeometry(QRect(90, 160, 61, 21));
        track1_Start = new QComboBox(gp_Track1);
        track1_Start->setObjectName(QString::fromUtf8("track1_Start"));
        track1_Start->setGeometry(QRect(160, 130, 121, 25));
        label_track1_Start = new QLabel(gp_Track1);
        label_track1_Start->setObjectName(QString::fromUtf8("label_track1_Start"));
        label_track1_Start->setGeometry(QRect(90, 130, 61, 21));
        track1_Measure = new QComboBox(gp_Track1);
        track1_Measure->setObjectName(QString::fromUtf8("track1_Measure"));
        track1_Measure->setGeometry(QRect(160, 190, 121, 25));
        label_track1_Measure = new QLabel(gp_Track1);
        label_track1_Measure->setObjectName(QString::fromUtf8("label_track1_Measure"));
        label_track1_Measure->setGeometry(QRect(90, 190, 61, 21));
        track1_LoopSync = new QCheckBox(gp_Track1);
        track1_LoopSync->setObjectName(QString::fromUtf8("track1_LoopSync"));
        track1_LoopSync->setGeometry(QRect(70, 220, 101, 21));
        track1_LoopSync->setLayoutDirection(Qt::RightToLeft);
        track1_TempoSync = new QCheckBox(gp_Track1);
        track1_TempoSync->setObjectName(QString::fromUtf8("track1_TempoSync"));
        track1_TempoSync->setGeometry(QRect(60, 240, 111, 23));
        track1_TempoSync->setLayoutDirection(Qt::RightToLeft);
        label_track1_Output = new QLabel(gp_Track1);
        label_track1_Output->setObjectName(QString::fromUtf8("label_track1_Output"));
        label_track1_Output->setGeometry(QRect(80, 300, 71, 21));
        track1_Input = new QComboBox(gp_Track1);
        track1_Input->setObjectName(QString::fromUtf8("track1_Input"));
        track1_Input->setGeometry(QRect(160, 270, 121, 25));
        track1_Output = new QComboBox(gp_Track1);
        track1_Output->setObjectName(QString::fromUtf8("track1_Output"));
        track1_Output->setGeometry(QRect(160, 300, 121, 25));
        label_track1_Input = new QLabel(gp_Track1);
        label_track1_Input->setObjectName(QString::fromUtf8("label_track1_Input"));
        label_track1_Input->setGeometry(QRect(80, 270, 71, 21));
        label_track1_PlyLevel = new QLabel(gp_Track1);
        label_track1_PlyLevel->setObjectName(QString::fromUtf8("label_track1_PlyLevel"));
        label_track1_PlyLevel->setGeometry(QRect(10, 310, 41, 21));
        label_track1_PlyLevel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        gp_Track2 = new QGroupBox(BossRc500Dialog);
        gp_Track2->setObjectName(QString::fromUtf8("gp_Track2"));
        gp_Track2->setGeometry(QRect(320, 100, 301, 341));
        track2_Measure = new QComboBox(gp_Track2);
        track2_Measure->setObjectName(QString::fromUtf8("track2_Measure"));
        track2_Measure->setGeometry(QRect(170, 190, 121, 25));
        label_track2_Stop = new QLabel(gp_Track2);
        label_track2_Stop->setObjectName(QString::fromUtf8("label_track2_Stop"));
        label_track2_Stop->setGeometry(QRect(90, 160, 71, 21));
        label_track2_Output = new QLabel(gp_Track2);
        label_track2_Output->setObjectName(QString::fromUtf8("label_track2_Output"));
        label_track2_Output->setGeometry(QRect(100, 300, 71, 21));
        track2_Stop = new QComboBox(gp_Track2);
        track2_Stop->setObjectName(QString::fromUtf8("track2_Stop"));
        track2_Stop->setGeometry(QRect(170, 160, 121, 25));
        track2_Pan = new QComboBox(gp_Track2);
        track2_Pan->setObjectName(QString::fromUtf8("track2_Pan"));
        track2_Pan->setGeometry(QRect(170, 100, 91, 25));
        track2_OneShot = new QCheckBox(gp_Track2);
        track2_OneShot->setObjectName(QString::fromUtf8("track2_OneShot"));
        track2_OneShot->setGeometry(QRect(90, 70, 91, 23));
        track2_OneShot->setLayoutDirection(Qt::RightToLeft);
        track2_TempoSync = new QCheckBox(gp_Track2);
        track2_TempoSync->setObjectName(QString::fromUtf8("track2_TempoSync"));
        track2_TempoSync->setGeometry(QRect(70, 240, 111, 23));
        track2_TempoSync->setLayoutDirection(Qt::RightToLeft);
        track2_LoopSync = new QCheckBox(gp_Track2);
        track2_LoopSync->setObjectName(QString::fromUtf8("track2_LoopSync"));
        track2_LoopSync->setGeometry(QRect(80, 220, 101, 21));
        track2_LoopSync->setLayoutDirection(Qt::RightToLeft);
        label_track2_Measure = new QLabel(gp_Track2);
        label_track2_Measure->setObjectName(QString::fromUtf8("label_track2_Measure"));
        label_track2_Measure->setGeometry(QRect(90, 190, 71, 21));
        track2_Output = new QComboBox(gp_Track2);
        track2_Output->setObjectName(QString::fromUtf8("track2_Output"));
        track2_Output->setGeometry(QRect(170, 300, 121, 25));
        label_track2_Start = new QLabel(gp_Track2);
        label_track2_Start->setObjectName(QString::fromUtf8("label_track2_Start"));
        label_track2_Start->setGeometry(QRect(90, 130, 71, 21));
        label_track2_Input = new QLabel(gp_Track2);
        label_track2_Input->setObjectName(QString::fromUtf8("label_track2_Input"));
        label_track2_Input->setGeometry(QRect(90, 270, 71, 21));
        track2_Reverse = new QCheckBox(gp_Track2);
        track2_Reverse->setObjectName(QString::fromUtf8("track2_Reverse"));
        track2_Reverse->setGeometry(QRect(100, 30, 81, 23));
        track2_Reverse->setLayoutDirection(Qt::RightToLeft);
        track2_Start = new QComboBox(gp_Track2);
        track2_Start->setObjectName(QString::fromUtf8("track2_Start"));
        track2_Start->setGeometry(QRect(170, 130, 121, 25));
        track2_Input = new QComboBox(gp_Track2);
        track2_Input->setObjectName(QString::fromUtf8("track2_Input"));
        track2_Input->setGeometry(QRect(170, 270, 121, 25));
        track2_LoopFx = new QCheckBox(gp_Track2);
        track2_LoopFx->setObjectName(QString::fromUtf8("track2_LoopFx"));
        track2_LoopFx->setGeometry(QRect(100, 50, 81, 23));
        track2_LoopFx->setLayoutDirection(Qt::RightToLeft);
        track2_LoopFx->setAutoFillBackground(false);
        track2_Level = new QSlider(gp_Track2);
        track2_Level->setObjectName(QString::fromUtf8("track2_Level"));
        track2_Level->setGeometry(QRect(10, 30, 41, 251));
        track2_Level->setMaximum(200);
        track2_Level->setOrientation(Qt::Vertical);
        track2_Level->setTickPosition(QSlider::TicksBothSides);
        label_track2_Level = new QLabel(gp_Track2);
        label_track2_Level->setObjectName(QString::fromUtf8("label_track2_Level"));
        label_track2_Level->setGeometry(QRect(10, 290, 41, 21));
        label_track2_Pan = new QLabel(gp_Track2);
        label_track2_Pan->setObjectName(QString::fromUtf8("label_track2_Pan"));
        label_track2_Pan->setGeometry(QRect(90, 100, 71, 21));
        label_track2_PlyLevel = new QLabel(gp_Track2);
        label_track2_PlyLevel->setObjectName(QString::fromUtf8("label_track2_PlyLevel"));
        label_track2_PlyLevel->setGeometry(QRect(10, 310, 41, 21));
        label_track2_PlyLevel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        button_Copy = new QPushButton(BossRc500Dialog);
        button_Copy->setObjectName(QString::fromUtf8("button_Copy"));
        button_Copy->setGeometry(QRect(640, 50, 51, 24));
        gp_Record = new QGroupBox(BossRc500Dialog);
        gp_Record->setObjectName(QString::fromUtf8("gp_Record"));
        gp_Record->setGeometry(QRect(10, 450, 301, 241));
        label_record_DubMode = new QLabel(gp_Record);
        label_record_DubMode->setObjectName(QString::fromUtf8("label_record_DubMode"));
        label_record_DubMode->setGeometry(QRect(10, 30, 121, 21));
        record_DubMode = new QComboBox(gp_Record);
        record_DubMode->setObjectName(QString::fromUtf8("record_DubMode"));
        record_DubMode->setGeometry(QRect(170, 30, 121, 25));
        record_Quantize = new QComboBox(gp_Record);
        record_Quantize->setObjectName(QString::fromUtf8("record_Quantize"));
        record_Quantize->setGeometry(QRect(170, 90, 121, 25));
        label_record_Quantize = new QLabel(gp_Record);
        label_record_Quantize->setObjectName(QString::fromUtf8("label_record_Quantize"));
        label_record_Quantize->setGeometry(QRect(10, 90, 121, 21));
        record_RecordAction = new QComboBox(gp_Record);
        record_RecordAction->setObjectName(QString::fromUtf8("record_RecordAction"));
        record_RecordAction->setGeometry(QRect(170, 60, 121, 25));
        label_record_RecordAction = new QLabel(gp_Record);
        label_record_RecordAction->setObjectName(QString::fromUtf8("label_record_RecordAction"));
        label_record_RecordAction->setGeometry(QRect(10, 60, 121, 21));
        record_AutoRecord = new QCheckBox(gp_Record);
        record_AutoRecord->setObjectName(QString::fromUtf8("record_AutoRecord"));
        record_AutoRecord->setGeometry(QRect(60, 120, 121, 21));
        record_AutoRecord->setLayoutDirection(Qt::RightToLeft);
        label_record_AutoRecordSource = new QLabel(gp_Record);
        label_record_AutoRecordSource->setObjectName(QString::fromUtf8("label_record_AutoRecordSource"));
        label_record_AutoRecordSource->setGeometry(QRect(10, 180, 151, 21));
        record_AutoRecordSource = new QComboBox(gp_Record);
        record_AutoRecordSource->setObjectName(QString::fromUtf8("record_AutoRecordSource"));
        record_AutoRecordSource->setGeometry(QRect(170, 180, 121, 25));
        label_record_Input_3 = new QLabel(gp_Record);
        label_record_Input_3->setObjectName(QString::fromUtf8("label_record_Input_3"));
        label_record_Input_3->setGeometry(QRect(10, 150, 161, 21));
        label_record_LoopLength = new QLabel(gp_Record);
        label_record_LoopLength->setObjectName(QString::fromUtf8("label_record_LoopLength"));
        label_record_LoopLength->setGeometry(QRect(10, 210, 141, 21));
        record_LoopLength = new QComboBox(gp_Record);
        record_LoopLength->setObjectName(QString::fromUtf8("record_LoopLength"));
        record_LoopLength->setGeometry(QRect(170, 210, 121, 25));
        record_AutoRecordSensitivity = new QSpinBox(gp_Record);
        record_AutoRecordSensitivity->setObjectName(QString::fromUtf8("record_AutoRecordSensitivity"));
        record_AutoRecordSensitivity->setGeometry(QRect(170, 150, 71, 24));
        record_AutoRecordSensitivity->setLayoutDirection(Qt::LeftToRight);
        record_AutoRecordSensitivity->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        record_AutoRecordSensitivity->setMaximum(100);
        gp_Play = new QGroupBox(BossRc500Dialog);
        gp_Play->setObjectName(QString::fromUtf8("gp_Play"));
        gp_Play->setGeometry(QRect(320, 450, 291, 211));
        label_play_PlayMode = new QLabel(gp_Play);
        label_play_PlayMode->setObjectName(QString::fromUtf8("label_play_PlayMode"));
        label_play_PlayMode->setGeometry(QRect(10, 30, 121, 21));
        play_PlayMode = new QComboBox(gp_Play);
        play_PlayMode->setObjectName(QString::fromUtf8("play_PlayMode"));
        play_PlayMode->setGeometry(QRect(160, 30, 121, 25));
        label_play_Level = new QLabel(gp_Play);
        label_play_Level->setObjectName(QString::fromUtf8("label_play_Level"));
        label_play_Level->setGeometry(QRect(10, 90, 141, 21));
        play_SingleChange = new QComboBox(gp_Play);
        play_SingleChange->setObjectName(QString::fromUtf8("play_SingleChange"));
        play_SingleChange->setGeometry(QRect(160, 60, 121, 25));
        label_play_SingleChange = new QLabel(gp_Play);
        label_play_SingleChange->setObjectName(QString::fromUtf8("label_play_SingleChange"));
        label_play_SingleChange->setGeometry(QRect(10, 60, 121, 21));
        label_play_AllStart = new QLabel(gp_Play);
        label_play_AllStart->setObjectName(QString::fromUtf8("label_play_AllStart"));
        label_play_AllStart->setGeometry(QRect(10, 150, 141, 21));
        play_FadeTime = new QComboBox(gp_Play);
        play_FadeTime->setObjectName(QString::fromUtf8("play_FadeTime"));
        play_FadeTime->setGeometry(QRect(160, 120, 121, 25));
        play_AllStart = new QComboBox(gp_Play);
        play_AllStart->setObjectName(QString::fromUtf8("play_AllStart"));
        play_AllStart->setGeometry(QRect(160, 150, 121, 25));
        label_play_FadeTime = new QLabel(gp_Play);
        label_play_FadeTime->setObjectName(QString::fromUtf8("label_play_FadeTime"));
        label_play_FadeTime->setGeometry(QRect(10, 120, 131, 21));
        label_play_TrackChain = new QLabel(gp_Play);
        label_play_TrackChain->setObjectName(QString::fromUtf8("label_play_TrackChain"));
        label_play_TrackChain->setGeometry(QRect(10, 180, 141, 21));
        play_TrackChain = new QComboBox(gp_Play);
        play_TrackChain->setObjectName(QString::fromUtf8("play_TrackChain"));
        play_TrackChain->setGeometry(QRect(160, 180, 121, 25));
        play_Level = new QSpinBox(gp_Play);
        play_Level->setObjectName(QString::fromUtf8("play_Level"));
        play_Level->setGeometry(QRect(160, 90, 71, 24));
        play_Level->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        play_Level->setMaximum(100);
        gp_Rhythm = new QGroupBox(BossRc500Dialog);
        gp_Rhythm->setObjectName(QString::fromUtf8("gp_Rhythm"));
        gp_Rhythm->setGeometry(QRect(630, 100, 391, 391));
        rhythm_level = new QSlider(gp_Rhythm);
        rhythm_level->setObjectName(QString::fromUtf8("rhythm_level"));
        rhythm_level->setGeometry(QRect(10, 30, 41, 181));
        rhythm_level->setMaximum(200);
        rhythm_level->setOrientation(Qt::Vertical);
        rhythm_level->setTickPosition(QSlider::TicksBothSides);
        label_track1_Level_2 = new QLabel(gp_Rhythm);
        label_track1_Level_2->setObjectName(QString::fromUtf8("label_track1_Level_2"));
        label_track1_Level_2->setGeometry(QRect(10, 220, 41, 21));
        label_track1_Level_3 = new QLabel(gp_Rhythm);
        label_track1_Level_3->setObjectName(QString::fromUtf8("label_track1_Level_3"));
        label_track1_Level_3->setGeometry(QRect(70, 220, 51, 21));
        rhythm_reverb = new QSlider(gp_Rhythm);
        rhythm_reverb->setObjectName(QString::fromUtf8("rhythm_reverb"));
        rhythm_reverb->setGeometry(QRect(70, 30, 41, 181));
        rhythm_reverb->setMaximum(200);
        rhythm_reverb->setOrientation(Qt::Vertical);
        rhythm_reverb->setTickPosition(QSlider::TicksBothSides);
        track1_Start_2 = new QComboBox(gp_Rhythm);
        track1_Start_2->setObjectName(QString::fromUtf8("track1_Start_2"));
        track1_Start_2->setGeometry(QRect(230, 30, 151, 25));
        label_track1_Start_2 = new QLabel(gp_Rhythm);
        label_track1_Start_2->setObjectName(QString::fromUtf8("label_track1_Start_2"));
        label_track1_Start_2->setGeometry(QRect(130, 30, 91, 21));
        track1_Start_3 = new QComboBox(gp_Rhythm);
        track1_Start_3->setObjectName(QString::fromUtf8("track1_Start_3"));
        track1_Start_3->setGeometry(QRect(230, 60, 41, 25));
        label_track1_Start_3 = new QLabel(gp_Rhythm);
        label_track1_Start_3->setObjectName(QString::fromUtf8("label_track1_Start_3"));
        label_track1_Start_3->setGeometry(QRect(130, 60, 91, 21));
        track1_Start_4 = new QComboBox(gp_Rhythm);
        track1_Start_4->setObjectName(QString::fromUtf8("track1_Start_4"));
        track1_Start_4->setGeometry(QRect(230, 90, 151, 25));
        label_track1_Start_4 = new QLabel(gp_Rhythm);
        label_track1_Start_4->setObjectName(QString::fromUtf8("label_track1_Start_4"));
        label_track1_Start_4->setGeometry(QRect(130, 90, 91, 21));
        label_track1_Start_5 = new QLabel(gp_Rhythm);
        label_track1_Start_5->setObjectName(QString::fromUtf8("label_track1_Start_5"));
        label_track1_Start_5->setGeometry(QRect(130, 120, 91, 21));
        track1_Start_5 = new QComboBox(gp_Rhythm);
        track1_Start_5->setObjectName(QString::fromUtf8("track1_Start_5"));
        track1_Start_5->setGeometry(QRect(230, 120, 151, 25));
        label_track1_Start_6 = new QLabel(gp_Rhythm);
        label_track1_Start_6->setObjectName(QString::fromUtf8("label_track1_Start_6"));
        label_track1_Start_6->setGeometry(QRect(130, 150, 91, 21));
        track1_Start_6 = new QComboBox(gp_Rhythm);
        track1_Start_6->setObjectName(QString::fromUtf8("track1_Start_6"));
        track1_Start_6->setGeometry(QRect(230, 150, 151, 25));
        label_track1_Start_7 = new QLabel(gp_Rhythm);
        label_track1_Start_7->setObjectName(QString::fromUtf8("label_track1_Start_7"));
        label_track1_Start_7->setGeometry(QRect(130, 180, 91, 21));
        track1_Start_7 = new QComboBox(gp_Rhythm);
        track1_Start_7->setObjectName(QString::fromUtf8("track1_Start_7"));
        track1_Start_7->setGeometry(QRect(230, 180, 151, 25));
        label_track1_Start_8 = new QLabel(gp_Rhythm);
        label_track1_Start_8->setObjectName(QString::fromUtf8("label_track1_Start_8"));
        label_track1_Start_8->setGeometry(QRect(130, 210, 91, 21));
        track1_Start_8 = new QComboBox(gp_Rhythm);
        track1_Start_8->setObjectName(QString::fromUtf8("track1_Start_8"));
        track1_Start_8->setGeometry(QRect(230, 210, 151, 25));
        track1_Start_9 = new QComboBox(gp_Rhythm);
        track1_Start_9->setObjectName(QString::fromUtf8("track1_Start_9"));
        track1_Start_9->setGeometry(QRect(230, 240, 151, 25));
        label_track1_Start_9 = new QLabel(gp_Rhythm);
        label_track1_Start_9->setObjectName(QString::fromUtf8("label_track1_Start_9"));
        label_track1_Start_9->setGeometry(QRect(130, 240, 91, 21));
        label_track1_Start_10 = new QLabel(gp_Rhythm);
        label_track1_Start_10->setObjectName(QString::fromUtf8("label_track1_Start_10"));
        label_track1_Start_10->setGeometry(QRect(130, 270, 91, 21));
        track1_Start_10 = new QComboBox(gp_Rhythm);
        track1_Start_10->setObjectName(QString::fromUtf8("track1_Start_10"));
        track1_Start_10->setGeometry(QRect(230, 270, 151, 25));
        track2_Reverse_2 = new QCheckBox(gp_Rhythm);
        track2_Reverse_2->setObjectName(QString::fromUtf8("track2_Reverse_2"));
        track2_Reverse_2->setGeometry(QRect(130, 300, 111, 23));
        track2_Reverse_2->setLayoutDirection(Qt::RightToLeft);
        track2_Reverse_3 = new QCheckBox(gp_Rhythm);
        track2_Reverse_3->setObjectName(QString::fromUtf8("track2_Reverse_3"));
        track2_Reverse_3->setGeometry(QRect(230, 320, 31, 23));
        track2_Reverse_3->setLayoutDirection(Qt::RightToLeft);
        track2_Reverse_4 = new QCheckBox(gp_Rhythm);
        track2_Reverse_4->setObjectName(QString::fromUtf8("track2_Reverse_4"));
        track2_Reverse_4->setGeometry(QRect(270, 320, 31, 23));
        track2_Reverse_4->setLayoutDirection(Qt::RightToLeft);
        track2_Reverse_5 = new QCheckBox(gp_Rhythm);
        track2_Reverse_5->setObjectName(QString::fromUtf8("track2_Reverse_5"));
        track2_Reverse_5->setGeometry(QRect(310, 320, 31, 23));
        track2_Reverse_5->setLayoutDirection(Qt::RightToLeft);
        track2_Reverse_6 = new QCheckBox(gp_Rhythm);
        track2_Reverse_6->setObjectName(QString::fromUtf8("track2_Reverse_6"));
        track2_Reverse_6->setGeometry(QRect(350, 320, 31, 23));
        track2_Reverse_6->setLayoutDirection(Qt::RightToLeft);
        label_track1_Start_11 = new QLabel(gp_Rhythm);
        label_track1_Start_11->setObjectName(QString::fromUtf8("label_track1_Start_11"));
        label_track1_Start_11->setGeometry(QRect(130, 320, 91, 21));
        label_track1_Start_12 = new QLabel(gp_Rhythm);
        label_track1_Start_12->setObjectName(QString::fromUtf8("label_track1_Start_12"));
        label_track1_Start_12->setGeometry(QRect(20, 360, 111, 21));
        track1_Level_4 = new QSlider(gp_Rhythm);
        track1_Level_4->setObjectName(QString::fromUtf8("track1_Level_4"));
        track1_Level_4->setGeometry(QRect(10, 250, 51, 111));
        track1_Level_4->setMinimum(-10);
        track1_Level_4->setMaximum(10);
        track1_Level_4->setPageStep(2);
        track1_Level_4->setOrientation(Qt::Vertical);
        track1_Level_4->setTickPosition(QSlider::TicksBothSides);
        track1_Level_5 = new QSlider(gp_Rhythm);
        track1_Level_5->setObjectName(QString::fromUtf8("track1_Level_5"));
        track1_Level_5->setGeometry(QRect(70, 250, 51, 111));
        track1_Level_5->setMinimum(-10);
        track1_Level_5->setMaximum(10);
        track1_Level_5->setPageStep(2);
        track1_Level_5->setTracking(false);
        track1_Level_5->setOrientation(Qt::Vertical);
        track1_Level_5->setTickPosition(QSlider::TicksBothSides);
        gb_LoopFx = new QGroupBox(BossRc500Dialog);
        gb_LoopFx->setObjectName(QString::fromUtf8("gb_LoopFx"));
        gb_LoopFx->setGeometry(QRect(630, 490, 231, 211));
        label_loopFx_Type = new QLabel(gb_LoopFx);
        label_loopFx_Type->setObjectName(QString::fromUtf8("label_loopFx_Type"));
        label_loopFx_Type->setGeometry(QRect(10, 60, 71, 21));
        loopFx_Type = new QComboBox(gb_LoopFx);
        loopFx_Type->setObjectName(QString::fromUtf8("loopFx_Type"));
        loopFx_Type->setGeometry(QRect(80, 60, 141, 25));
        label_loopFx_ScatLen = new QLabel(gb_LoopFx);
        label_loopFx_ScatLen->setObjectName(QString::fromUtf8("label_loopFx_ScatLen"));
        label_loopFx_ScatLen->setGeometry(QRect(10, 90, 71, 21));
        loopFx_ScatLen = new QComboBox(gb_LoopFx);
        loopFx_ScatLen->setObjectName(QString::fromUtf8("loopFx_ScatLen"));
        loopFx_ScatLen->setGeometry(QRect(80, 90, 141, 25));
        loopFx_ReptLen = new QComboBox(gb_LoopFx);
        loopFx_ReptLen->setObjectName(QString::fromUtf8("loopFx_ReptLen"));
        loopFx_ReptLen->setGeometry(QRect(80, 120, 141, 25));
        label_loopFx_ReptLen = new QLabel(gb_LoopFx);
        label_loopFx_ReptLen->setObjectName(QString::fromUtf8("label_loopFx_ReptLen"));
        label_loopFx_ReptLen->setGeometry(QRect(10, 120, 71, 21));
        label_loopFx_Shift = new QLabel(gb_LoopFx);
        label_loopFx_Shift->setObjectName(QString::fromUtf8("label_loopFx_Shift"));
        label_loopFx_Shift->setGeometry(QRect(10, 150, 71, 21));
        loopFx_Shift = new QComboBox(gb_LoopFx);
        loopFx_Shift->setObjectName(QString::fromUtf8("loopFx_Shift"));
        loopFx_Shift->setGeometry(QRect(80, 150, 141, 25));
        label_loopFx_Flick = new QLabel(gb_LoopFx);
        label_loopFx_Flick->setObjectName(QString::fromUtf8("label_loopFx_Flick"));
        label_loopFx_Flick->setGeometry(QRect(10, 180, 61, 21));
        loopFx_Flick = new QSpinBox(gb_LoopFx);
        loopFx_Flick->setObjectName(QString::fromUtf8("loopFx_Flick"));
        loopFx_Flick->setGeometry(QRect(80, 180, 61, 24));
        loopFx_Flick->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        loopFx_Flick->setMaximum(100);
        loopFx_Sw = new QCheckBox(gb_LoopFx);
        loopFx_Sw->setObjectName(QString::fromUtf8("loopFx_Sw"));
        loopFx_Sw->setGeometry(QRect(10, 30, 81, 21));
        loopFx_Sw->setLayoutDirection(Qt::RightToLeft);

        retranslateUi(BossRc500Dialog);

        QMetaObject::connectSlotsByName(BossRc500Dialog);
    } // setupUi

    void retranslateUi(QDialog *BossRc500Dialog)
    {
        BossRc500Dialog->setWindowTitle(QCoreApplication::translate("BossRc500Dialog", "Dialog", nullptr));
        label_File->setText(QCoreApplication::translate("BossRc500Dialog", "File", nullptr));
        button_Open->setText(QCoreApplication::translate("BossRc500Dialog", "Open", nullptr));
        label_LoopStation->setText(QString());
        button_Save->setText(QCoreApplication::translate("BossRc500Dialog", "Save", nullptr));
        label_To->setText(QCoreApplication::translate("BossRc500Dialog", "To", nullptr));
        button_Quit->setText(QCoreApplication::translate("BossRc500Dialog", "Quit", nullptr));
        label_Memory->setText(QCoreApplication::translate("BossRc500Dialog", "Memory", nullptr));
        label_CopyTo->setText(QCoreApplication::translate("BossRc500Dialog", "From", nullptr));
        label_Filename->setText(QCoreApplication::translate("BossRc500Dialog", "<filename>", nullptr));
        label_Boss->setText(QString());
        gp_Track1->setTitle(QCoreApplication::translate("BossRc500Dialog", "TRACK 1", nullptr));
        track1_Reverse->setText(QCoreApplication::translate("BossRc500Dialog", "Reverse", nullptr));
        label_track1_Level->setText(QCoreApplication::translate("BossRc500Dialog", "Level", nullptr));
        track1_LoopFx->setText(QCoreApplication::translate("BossRc500Dialog", "Loop Fx", nullptr));
        track1_OneShot->setText(QCoreApplication::translate("BossRc500Dialog", "One Shot", nullptr));
        label_track1_Pan->setText(QCoreApplication::translate("BossRc500Dialog", "Pan", nullptr));
        label_track1_Stop->setText(QCoreApplication::translate("BossRc500Dialog", "Stop", nullptr));
        label_track1_Start->setText(QCoreApplication::translate("BossRc500Dialog", "Start", nullptr));
        label_track1_Measure->setText(QCoreApplication::translate("BossRc500Dialog", "Measure", nullptr));
        track1_LoopSync->setText(QCoreApplication::translate("BossRc500Dialog", "Loop Sync", nullptr));
        track1_TempoSync->setText(QCoreApplication::translate("BossRc500Dialog", "Tempo  Sync", nullptr));
        label_track1_Output->setText(QCoreApplication::translate("BossRc500Dialog", "Output", nullptr));
        label_track1_Input->setText(QCoreApplication::translate("BossRc500Dialog", "Input", nullptr));
        label_track1_PlyLevel->setText(QCoreApplication::translate("BossRc500Dialog", "0", nullptr));
        gp_Track2->setTitle(QCoreApplication::translate("BossRc500Dialog", "TRACK 2", nullptr));
        label_track2_Stop->setText(QCoreApplication::translate("BossRc500Dialog", "Stop", nullptr));
        label_track2_Output->setText(QCoreApplication::translate("BossRc500Dialog", "Output", nullptr));
        track2_OneShot->setText(QCoreApplication::translate("BossRc500Dialog", "One Shot", nullptr));
        track2_TempoSync->setText(QCoreApplication::translate("BossRc500Dialog", "Tempo  Sync", nullptr));
        track2_LoopSync->setText(QCoreApplication::translate("BossRc500Dialog", "Loop Sync", nullptr));
        label_track2_Measure->setText(QCoreApplication::translate("BossRc500Dialog", "Measure", nullptr));
        label_track2_Start->setText(QCoreApplication::translate("BossRc500Dialog", "Start", nullptr));
        label_track2_Input->setText(QCoreApplication::translate("BossRc500Dialog", "Input", nullptr));
        track2_Reverse->setText(QCoreApplication::translate("BossRc500Dialog", "Reverse", nullptr));
        track2_LoopFx->setText(QCoreApplication::translate("BossRc500Dialog", "Loop Fx", nullptr));
        label_track2_Level->setText(QCoreApplication::translate("BossRc500Dialog", "Level", nullptr));
        label_track2_Pan->setText(QCoreApplication::translate("BossRc500Dialog", "Pan", nullptr));
        label_track2_PlyLevel->setText(QCoreApplication::translate("BossRc500Dialog", "0", nullptr));
        button_Copy->setText(QCoreApplication::translate("BossRc500Dialog", "Copy", nullptr));
        gp_Record->setTitle(QCoreApplication::translate("BossRc500Dialog", "RECORD", nullptr));
        label_record_DubMode->setText(QCoreApplication::translate("BossRc500Dialog", "Dub Mode", nullptr));
        label_record_Quantize->setText(QCoreApplication::translate("BossRc500Dialog", "Quantize", nullptr));
        label_record_RecordAction->setText(QCoreApplication::translate("BossRc500Dialog", "Record Action", nullptr));
        record_AutoRecord->setText(QCoreApplication::translate("BossRc500Dialog", "Auto Record", nullptr));
        label_record_AutoRecordSource->setText(QCoreApplication::translate("BossRc500Dialog", "Auto Record Source", nullptr));
        label_record_Input_3->setText(QCoreApplication::translate("BossRc500Dialog", "Auto Rec. Sensitivity", nullptr));
        label_record_LoopLength->setText(QCoreApplication::translate("BossRc500Dialog", "Loop Length", nullptr));
        gp_Play->setTitle(QCoreApplication::translate("BossRc500Dialog", "PLAY", nullptr));
        label_play_PlayMode->setText(QCoreApplication::translate("BossRc500Dialog", "Play Mode", nullptr));
        label_play_Level->setText(QCoreApplication::translate("BossRc500Dialog", "Level", nullptr));
        label_play_SingleChange->setText(QCoreApplication::translate("BossRc500Dialog", "Single Change", nullptr));
        label_play_AllStart->setText(QCoreApplication::translate("BossRc500Dialog", "All Start", nullptr));
        label_play_FadeTime->setText(QCoreApplication::translate("BossRc500Dialog", "Fade Time", nullptr));
        label_play_TrackChain->setText(QCoreApplication::translate("BossRc500Dialog", "Track Chain", nullptr));
        gp_Rhythm->setTitle(QCoreApplication::translate("BossRc500Dialog", "Rhythm", nullptr));
        label_track1_Level_2->setText(QCoreApplication::translate("BossRc500Dialog", "Level", nullptr));
        label_track1_Level_3->setText(QCoreApplication::translate("BossRc500Dialog", "Reverb", nullptr));
        label_track1_Start_2->setText(QCoreApplication::translate("BossRc500Dialog", "Pattern", nullptr));
        label_track1_Start_3->setText(QCoreApplication::translate("BossRc500Dialog", "Variation", nullptr));
        label_track1_Start_4->setText(QCoreApplication::translate("BossRc500Dialog", "Var. Change", nullptr));
        label_track1_Start_5->setText(QCoreApplication::translate("BossRc500Dialog", "Kit", nullptr));
        label_track1_Start_6->setText(QCoreApplication::translate("BossRc500Dialog", "Beat", nullptr));
        label_track1_Start_7->setText(QCoreApplication::translate("BossRc500Dialog", "Start", nullptr));
        label_track1_Start_8->setText(QCoreApplication::translate("BossRc500Dialog", "Stop", nullptr));
        label_track1_Start_9->setText(QCoreApplication::translate("BossRc500Dialog", "Rec Count", nullptr));
        label_track1_Start_10->setText(QCoreApplication::translate("BossRc500Dialog", "Play Count", nullptr));
        track2_Reverse_2->setText(QCoreApplication::translate("BossRc500Dialog", "Fill", nullptr));
        track2_Reverse_3->setText(QCoreApplication::translate("BossRc500Dialog", "1", nullptr));
        track2_Reverse_4->setText(QCoreApplication::translate("BossRc500Dialog", "2", nullptr));
        track2_Reverse_5->setText(QCoreApplication::translate("BossRc500Dialog", "3", nullptr));
        track2_Reverse_6->setText(QCoreApplication::translate("BossRc500Dialog", "4", nullptr));
        label_track1_Start_11->setText(QCoreApplication::translate("BossRc500Dialog", "Part", nullptr));
        label_track1_Start_12->setText(QCoreApplication::translate("BossRc500Dialog", "Low Tone High", nullptr));
        gb_LoopFx->setTitle(QCoreApplication::translate("BossRc500Dialog", "Loop Fx", nullptr));
        label_loopFx_Type->setText(QCoreApplication::translate("BossRc500Dialog", "Type", nullptr));
        label_loopFx_ScatLen->setText(QCoreApplication::translate("BossRc500Dialog", "Scat Len", nullptr));
        label_loopFx_ReptLen->setText(QCoreApplication::translate("BossRc500Dialog", "Rept Len", nullptr));
        label_loopFx_Shift->setText(QCoreApplication::translate("BossRc500Dialog", "Shift", nullptr));
        label_loopFx_Flick->setText(QCoreApplication::translate("BossRc500Dialog", "Flick", nullptr));
        loopFx_Sw->setText(QCoreApplication::translate("BossRc500Dialog", "Loop Fx", nullptr));
    } // retranslateUi

};

QT_END_NAMESPACE

#endif // BOSS_2D_RC500XKRPPK_H
