/********************************************************************************
** Form generated from reading UI file 'Boss-rc500-systemlaohvg.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef BOSS_2D_RC500_2D_SYSTEMLAOHVG_H
#define BOSS_2D_RC500_2D_SYSTEMLAOHVG_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>

QT_BEGIN_NAMESPACE

class Ui_BossRc500SystemDialog
{
public:
    QGroupBox *gp_General;
    QLabel *label_general_DisplayContrast;
    QComboBox *general_DisplayMode;
    QLabel *label_general_DisplayMode;
    QLabel *label_general_UndoREdo;
    QComboBox *general_UndoRedo;
    QSpinBox *general_DisplayContrast;
    QGroupBox *gp_Preference;
    QLabel *label_Pref_Pedal1Pref;
    QComboBox *pref_Pedal1Pref;
    QComboBox *pref_Pedal2Pref;
    QLabel *label_Pref_Pedal2Pref;
    QLabel *label_Pref_Pedal3Pref;
    QComboBox *pref_Pedal3Pref;
    QComboBox *pref_Ctl1Pref;
    QLabel *label_Pref_Ctl1Pref;
    QComboBox *pref_Ctl2Pref;
    QLabel *label_Pref_Ctl2Pref;
    QLabel *label_Pref_ExpPref;
    QComboBox *pref_ExpPref;
    QGroupBox *gp_Midi;
    QComboBox *midi_RxNoteCh;
    QLabel *label_midi_RxNoteCh;
    QLabel *label_midi_TxChannel;
    QComboBox *midi_TxChannel;
    QLabel *label_midi_SyncClock;
    QLabel *label_midi_RxCtlChannel;
    QSpinBox *midi_RxCtlChannel;
    QComboBox *midi_SyncClock;
    QCheckBox *midi_ClockOut;
    QComboBox *midi_SyncClock_2;
    QLabel *label_midi_SyncClock_2;
    QCheckBox *midi_PcOut;
    QLabel *label_midi_MidiThru;
    QComboBox *midi_MidiThru;
    QLabel *label_midi_UsbThru;
    QComboBox *midi_UsbThru;
    QCheckBox *midi_Omni;
    QGroupBox *gp_Extent;
    QLabel *label_extent_Extent1;
    QLabel *label_extent_Extent2;
    QLabel *label_extent_Extent3;
    QLabel *label_extent_Extent4;
    QLabel *label_extent_Extent5;
    QSpinBox *extent_Extent1Min;
    QLabel *label_extent_Extent;
    QComboBox *extent_Extent;
    QLabel *label_extent_ExtentMax;
    QSpinBox *extent_Extent1Max;
    QSpinBox *extent_Extent2Max;
    QLabel *label_extent_ExtentMin;
    QSpinBox *extent_Extent2Min;
    QSpinBox *extent_Extent3Max;
    QSpinBox *extent_Extent3Min;
    QSpinBox *extent_Extent4Max;
    QSpinBox *extent_Extent4Min;
    QSpinBox *extent_Extent5Max;
    QSpinBox *extent_Extent5Min;
    QGroupBox *gp_Input;
    QCheckBox *input_Phantom;
    QLabel *label_input_MicroIn;
    QComboBox *input_MicroIn;
    QComboBox *input_InstrumentIn;
    QLabel *label_input_InstrIn;
    QLabel *label_input_Rhythm;
    QComboBox *input_Rhythm;
    QLabel *label_input_MicroInNs;
    QLabel *label_input_PeakSource;
    QSpinBox *input_PeakSource;
    QSpinBox *input_MicroInNs;
    QLabel *label_input_InstrInNs;
    QSpinBox *input_InstrInNs;
    QPushButton *button_Apply;
    QPushButton *button_Cancel;

    void setupUi(QDialog *BossRc500SystemDialog)
    {
        if (BossRc500SystemDialog->objectName().isEmpty())
            BossRc500SystemDialog->setObjectName(QString::fromUtf8("BossRc500SystemDialog"));
        BossRc500SystemDialog->resize(885, 496);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(170, 49, 45, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        BossRc500SystemDialog->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("Bitstream Vera Sans"));
        font.setBold(true);
        font.setWeight(QFont::DemiBold);
        BossRc500SystemDialog->setFont(font);
        gp_General = new QGroupBox(BossRc500SystemDialog);
        gp_General->setObjectName(QString::fromUtf8("gp_General"));
        gp_General->setGeometry(QRect(10, 10, 281, 131));
        label_general_DisplayContrast = new QLabel(gp_General);
        label_general_DisplayContrast->setObjectName(QString::fromUtf8("label_general_DisplayContrast"));
        label_general_DisplayContrast->setGeometry(QRect(10, 30, 131, 21));
        general_DisplayMode = new QComboBox(gp_General);
        general_DisplayMode->setObjectName(QString::fromUtf8("general_DisplayMode"));
        general_DisplayMode->setGeometry(QRect(140, 60, 131, 25));
        label_general_DisplayMode = new QLabel(gp_General);
        label_general_DisplayMode->setObjectName(QString::fromUtf8("label_general_DisplayMode"));
        label_general_DisplayMode->setGeometry(QRect(10, 60, 101, 21));
        label_general_UndoREdo = new QLabel(gp_General);
        label_general_UndoREdo->setObjectName(QString::fromUtf8("label_general_UndoREdo"));
        label_general_UndoREdo->setGeometry(QRect(10, 90, 101, 21));
        general_UndoRedo = new QComboBox(gp_General);
        general_UndoRedo->setObjectName(QString::fromUtf8("general_UndoRedo"));
        general_UndoRedo->setGeometry(QRect(140, 90, 131, 25));
        general_DisplayContrast = new QSpinBox(gp_General);
        general_DisplayContrast->setObjectName(QString::fromUtf8("general_DisplayContrast"));
        general_DisplayContrast->setGeometry(QRect(140, 30, 61, 24));
        general_DisplayContrast->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        general_DisplayContrast->setMinimum(1);
        general_DisplayContrast->setMaximum(10);
        gp_Preference = new QGroupBox(BossRc500SystemDialog);
        gp_Preference->setObjectName(QString::fromUtf8("gp_Preference"));
        gp_Preference->setGeometry(QRect(300, 10, 281, 221));
        label_Pref_Pedal1Pref = new QLabel(gp_Preference);
        label_Pref_Pedal1Pref->setObjectName(QString::fromUtf8("label_Pref_Pedal1Pref"));
        label_Pref_Pedal1Pref->setGeometry(QRect(10, 30, 101, 21));
        pref_Pedal1Pref = new QComboBox(gp_Preference);
        pref_Pedal1Pref->setObjectName(QString::fromUtf8("pref_Pedal1Pref"));
        pref_Pedal1Pref->setGeometry(QRect(120, 30, 141, 25));
        pref_Pedal2Pref = new QComboBox(gp_Preference);
        pref_Pedal2Pref->setObjectName(QString::fromUtf8("pref_Pedal2Pref"));
        pref_Pedal2Pref->setGeometry(QRect(120, 60, 141, 25));
        label_Pref_Pedal2Pref = new QLabel(gp_Preference);
        label_Pref_Pedal2Pref->setObjectName(QString::fromUtf8("label_Pref_Pedal2Pref"));
        label_Pref_Pedal2Pref->setGeometry(QRect(10, 60, 101, 21));
        label_Pref_Pedal3Pref = new QLabel(gp_Preference);
        label_Pref_Pedal3Pref->setObjectName(QString::fromUtf8("label_Pref_Pedal3Pref"));
        label_Pref_Pedal3Pref->setGeometry(QRect(10, 90, 101, 21));
        pref_Pedal3Pref = new QComboBox(gp_Preference);
        pref_Pedal3Pref->setObjectName(QString::fromUtf8("pref_Pedal3Pref"));
        pref_Pedal3Pref->setGeometry(QRect(120, 90, 141, 25));
        pref_Ctl1Pref = new QComboBox(gp_Preference);
        pref_Ctl1Pref->setObjectName(QString::fromUtf8("pref_Ctl1Pref"));
        pref_Ctl1Pref->setGeometry(QRect(120, 120, 141, 25));
        label_Pref_Ctl1Pref = new QLabel(gp_Preference);
        label_Pref_Ctl1Pref->setObjectName(QString::fromUtf8("label_Pref_Ctl1Pref"));
        label_Pref_Ctl1Pref->setGeometry(QRect(10, 120, 101, 21));
        pref_Ctl2Pref = new QComboBox(gp_Preference);
        pref_Ctl2Pref->setObjectName(QString::fromUtf8("pref_Ctl2Pref"));
        pref_Ctl2Pref->setGeometry(QRect(120, 150, 141, 25));
        label_Pref_Ctl2Pref = new QLabel(gp_Preference);
        label_Pref_Ctl2Pref->setObjectName(QString::fromUtf8("label_Pref_Ctl2Pref"));
        label_Pref_Ctl2Pref->setGeometry(QRect(10, 150, 101, 21));
        label_Pref_ExpPref = new QLabel(gp_Preference);
        label_Pref_ExpPref->setObjectName(QString::fromUtf8("label_Pref_ExpPref"));
        label_Pref_ExpPref->setGeometry(QRect(10, 180, 101, 21));
        pref_ExpPref = new QComboBox(gp_Preference);
        pref_ExpPref->setObjectName(QString::fromUtf8("pref_ExpPref"));
        pref_ExpPref->setGeometry(QRect(120, 180, 141, 25));
        gp_Midi = new QGroupBox(BossRc500SystemDialog);
        gp_Midi->setObjectName(QString::fromUtf8("gp_Midi"));
        gp_Midi->setGeometry(QRect(590, 10, 281, 331));
        midi_RxNoteCh = new QComboBox(gp_Midi);
        midi_RxNoteCh->setObjectName(QString::fromUtf8("midi_RxNoteCh"));
        midi_RxNoteCh->setGeometry(QRect(130, 90, 141, 25));
        label_midi_RxNoteCh = new QLabel(gp_Midi);
        label_midi_RxNoteCh->setObjectName(QString::fromUtf8("label_midi_RxNoteCh"));
        label_midi_RxNoteCh->setGeometry(QRect(10, 90, 101, 21));
        label_midi_TxChannel = new QLabel(gp_Midi);
        label_midi_TxChannel->setObjectName(QString::fromUtf8("label_midi_TxChannel"));
        label_midi_TxChannel->setGeometry(QRect(10, 120, 101, 21));
        midi_TxChannel = new QComboBox(gp_Midi);
        midi_TxChannel->setObjectName(QString::fromUtf8("midi_TxChannel"));
        midi_TxChannel->setGeometry(QRect(130, 120, 141, 25));
        label_midi_SyncClock = new QLabel(gp_Midi);
        label_midi_SyncClock->setObjectName(QString::fromUtf8("label_midi_SyncClock"));
        label_midi_SyncClock->setGeometry(QRect(10, 150, 101, 21));
        label_midi_RxCtlChannel = new QLabel(gp_Midi);
        label_midi_RxCtlChannel->setObjectName(QString::fromUtf8("label_midi_RxCtlChannel"));
        label_midi_RxCtlChannel->setGeometry(QRect(10, 30, 111, 21));
        midi_RxCtlChannel = new QSpinBox(gp_Midi);
        midi_RxCtlChannel->setObjectName(QString::fromUtf8("midi_RxCtlChannel"));
        midi_RxCtlChannel->setGeometry(QRect(130, 30, 61, 24));
        midi_RxCtlChannel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        midi_RxCtlChannel->setMaximum(100);
        midi_SyncClock = new QComboBox(gp_Midi);
        midi_SyncClock->setObjectName(QString::fromUtf8("midi_SyncClock"));
        midi_SyncClock->setGeometry(QRect(130, 150, 141, 25));
        midi_ClockOut = new QCheckBox(gp_Midi);
        midi_ClockOut->setObjectName(QString::fromUtf8("midi_ClockOut"));
        midi_ClockOut->setGeometry(QRect(10, 180, 131, 23));
        midi_ClockOut->setLayoutDirection(Qt::RightToLeft);
        midi_SyncClock_2 = new QComboBox(gp_Midi);
        midi_SyncClock_2->setObjectName(QString::fromUtf8("midi_SyncClock_2"));
        midi_SyncClock_2->setGeometry(QRect(130, 210, 141, 25));
        label_midi_SyncClock_2 = new QLabel(gp_Midi);
        label_midi_SyncClock_2->setObjectName(QString::fromUtf8("label_midi_SyncClock_2"));
        label_midi_SyncClock_2->setGeometry(QRect(10, 210, 101, 21));
        midi_PcOut = new QCheckBox(gp_Midi);
        midi_PcOut->setObjectName(QString::fromUtf8("midi_PcOut"));
        midi_PcOut->setGeometry(QRect(10, 240, 131, 23));
        midi_PcOut->setLayoutDirection(Qt::RightToLeft);
        label_midi_MidiThru = new QLabel(gp_Midi);
        label_midi_MidiThru->setObjectName(QString::fromUtf8("label_midi_MidiThru"));
        label_midi_MidiThru->setGeometry(QRect(10, 270, 101, 21));
        midi_MidiThru = new QComboBox(gp_Midi);
        midi_MidiThru->setObjectName(QString::fromUtf8("midi_MidiThru"));
        midi_MidiThru->setGeometry(QRect(130, 270, 141, 25));
        label_midi_UsbThru = new QLabel(gp_Midi);
        label_midi_UsbThru->setObjectName(QString::fromUtf8("label_midi_UsbThru"));
        label_midi_UsbThru->setGeometry(QRect(10, 300, 101, 21));
        midi_UsbThru = new QComboBox(gp_Midi);
        midi_UsbThru->setObjectName(QString::fromUtf8("midi_UsbThru"));
        midi_UsbThru->setGeometry(QRect(130, 300, 141, 25));
        midi_Omni = new QCheckBox(gp_Midi);
        midi_Omni->setObjectName(QString::fromUtf8("midi_Omni"));
        midi_Omni->setGeometry(QRect(10, 60, 131, 23));
        midi_Omni->setLayoutDirection(Qt::RightToLeft);
        gp_Extent = new QGroupBox(BossRc500SystemDialog);
        gp_Extent->setObjectName(QString::fromUtf8("gp_Extent"));
        gp_Extent->setGeometry(QRect(10, 240, 281, 241));
        label_extent_Extent1 = new QLabel(gp_Extent);
        label_extent_Extent1->setObjectName(QString::fromUtf8("label_extent_Extent1"));
        label_extent_Extent1->setGeometry(QRect(20, 80, 101, 21));
        label_extent_Extent2 = new QLabel(gp_Extent);
        label_extent_Extent2->setObjectName(QString::fromUtf8("label_extent_Extent2"));
        label_extent_Extent2->setGeometry(QRect(20, 110, 101, 21));
        label_extent_Extent3 = new QLabel(gp_Extent);
        label_extent_Extent3->setObjectName(QString::fromUtf8("label_extent_Extent3"));
        label_extent_Extent3->setGeometry(QRect(20, 140, 101, 21));
        label_extent_Extent4 = new QLabel(gp_Extent);
        label_extent_Extent4->setObjectName(QString::fromUtf8("label_extent_Extent4"));
        label_extent_Extent4->setGeometry(QRect(20, 170, 101, 21));
        label_extent_Extent5 = new QLabel(gp_Extent);
        label_extent_Extent5->setObjectName(QString::fromUtf8("label_extent_Extent5"));
        label_extent_Extent5->setGeometry(QRect(20, 200, 101, 21));
        extent_Extent1Min = new QSpinBox(gp_Extent);
        extent_Extent1Min->setObjectName(QString::fromUtf8("extent_Extent1Min"));
        extent_Extent1Min->setGeometry(QRect(130, 80, 51, 26));
        extent_Extent1Min->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_extent_Extent = new QLabel(gp_Extent);
        label_extent_Extent->setObjectName(QString::fromUtf8("label_extent_Extent"));
        label_extent_Extent->setGeometry(QRect(20, 30, 101, 21));
        extent_Extent = new QComboBox(gp_Extent);
        extent_Extent->setObjectName(QString::fromUtf8("extent_Extent"));
        extent_Extent->setGeometry(QRect(130, 30, 141, 25));
        label_extent_ExtentMax = new QLabel(gp_Extent);
        label_extent_ExtentMax->setObjectName(QString::fromUtf8("label_extent_ExtentMax"));
        label_extent_ExtentMax->setGeometry(QRect(200, 60, 31, 21));
        extent_Extent1Max = new QSpinBox(gp_Extent);
        extent_Extent1Max->setObjectName(QString::fromUtf8("extent_Extent1Max"));
        extent_Extent1Max->setGeometry(QRect(190, 80, 51, 26));
        extent_Extent1Max->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        extent_Extent2Max = new QSpinBox(gp_Extent);
        extent_Extent2Max->setObjectName(QString::fromUtf8("extent_Extent2Max"));
        extent_Extent2Max->setGeometry(QRect(190, 110, 51, 26));
        extent_Extent2Max->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_extent_ExtentMin = new QLabel(gp_Extent);
        label_extent_ExtentMin->setObjectName(QString::fromUtf8("label_extent_ExtentMin"));
        label_extent_ExtentMin->setGeometry(QRect(140, 60, 31, 21));
        extent_Extent2Min = new QSpinBox(gp_Extent);
        extent_Extent2Min->setObjectName(QString::fromUtf8("extent_Extent2Min"));
        extent_Extent2Min->setGeometry(QRect(130, 110, 51, 26));
        extent_Extent2Min->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        extent_Extent3Max = new QSpinBox(gp_Extent);
        extent_Extent3Max->setObjectName(QString::fromUtf8("extent_Extent3Max"));
        extent_Extent3Max->setGeometry(QRect(190, 140, 51, 26));
        extent_Extent3Max->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        extent_Extent3Min = new QSpinBox(gp_Extent);
        extent_Extent3Min->setObjectName(QString::fromUtf8("extent_Extent3Min"));
        extent_Extent3Min->setGeometry(QRect(130, 140, 51, 26));
        extent_Extent3Min->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        extent_Extent4Max = new QSpinBox(gp_Extent);
        extent_Extent4Max->setObjectName(QString::fromUtf8("extent_Extent4Max"));
        extent_Extent4Max->setGeometry(QRect(190, 170, 51, 26));
        extent_Extent4Max->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        extent_Extent4Min = new QSpinBox(gp_Extent);
        extent_Extent4Min->setObjectName(QString::fromUtf8("extent_Extent4Min"));
        extent_Extent4Min->setGeometry(QRect(130, 170, 51, 26));
        extent_Extent4Min->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        extent_Extent5Max = new QSpinBox(gp_Extent);
        extent_Extent5Max->setObjectName(QString::fromUtf8("extent_Extent5Max"));
        extent_Extent5Max->setGeometry(QRect(190, 200, 51, 26));
        extent_Extent5Max->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        extent_Extent5Min = new QSpinBox(gp_Extent);
        extent_Extent5Min->setObjectName(QString::fromUtf8("extent_Extent5Min"));
        extent_Extent5Min->setGeometry(QRect(130, 200, 51, 26));
        extent_Extent5Min->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        gp_Input = new QGroupBox(BossRc500SystemDialog);
        gp_Input->setObjectName(QString::fromUtf8("gp_Input"));
        gp_Input->setGeometry(QRect(300, 240, 281, 241));
        input_Phantom = new QCheckBox(gp_Input);
        input_Phantom->setObjectName(QString::fromUtf8("input_Phantom"));
        input_Phantom->setGeometry(QRect(10, 30, 131, 23));
        input_Phantom->setLayoutDirection(Qt::RightToLeft);
        label_input_MicroIn = new QLabel(gp_Input);
        label_input_MicroIn->setObjectName(QString::fromUtf8("label_input_MicroIn"));
        label_input_MicroIn->setGeometry(QRect(20, 60, 101, 21));
        input_MicroIn = new QComboBox(gp_Input);
        input_MicroIn->setObjectName(QString::fromUtf8("input_MicroIn"));
        input_MicroIn->setGeometry(QRect(130, 60, 141, 25));
        input_InstrumentIn = new QComboBox(gp_Input);
        input_InstrumentIn->setObjectName(QString::fromUtf8("input_InstrumentIn"));
        input_InstrumentIn->setGeometry(QRect(130, 90, 141, 25));
        label_input_InstrIn = new QLabel(gp_Input);
        label_input_InstrIn->setObjectName(QString::fromUtf8("label_input_InstrIn"));
        label_input_InstrIn->setGeometry(QRect(20, 90, 101, 21));
        label_input_Rhythm = new QLabel(gp_Input);
        label_input_Rhythm->setObjectName(QString::fromUtf8("label_input_Rhythm"));
        label_input_Rhythm->setGeometry(QRect(20, 120, 101, 21));
        input_Rhythm = new QComboBox(gp_Input);
        input_Rhythm->setObjectName(QString::fromUtf8("input_Rhythm"));
        input_Rhythm->setGeometry(QRect(130, 120, 141, 25));
        label_input_MicroInNs = new QLabel(gp_Input);
        label_input_MicroInNs->setObjectName(QString::fromUtf8("label_input_MicroInNs"));
        label_input_MicroInNs->setGeometry(QRect(20, 150, 101, 21));
        label_input_PeakSource = new QLabel(gp_Input);
        label_input_PeakSource->setObjectName(QString::fromUtf8("label_input_PeakSource"));
        label_input_PeakSource->setGeometry(QRect(20, 210, 101, 21));
        input_PeakSource = new QSpinBox(gp_Input);
        input_PeakSource->setObjectName(QString::fromUtf8("input_PeakSource"));
        input_PeakSource->setGeometry(QRect(130, 210, 81, 26));
        input_PeakSource->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        input_MicroInNs = new QSpinBox(gp_Input);
        input_MicroInNs->setObjectName(QString::fromUtf8("input_MicroInNs"));
        input_MicroInNs->setGeometry(QRect(130, 150, 81, 26));
        input_MicroInNs->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_input_InstrInNs = new QLabel(gp_Input);
        label_input_InstrInNs->setObjectName(QString::fromUtf8("label_input_InstrInNs"));
        label_input_InstrInNs->setGeometry(QRect(20, 180, 101, 21));
        input_InstrInNs = new QSpinBox(gp_Input);
        input_InstrInNs->setObjectName(QString::fromUtf8("input_InstrInNs"));
        input_InstrInNs->setGeometry(QRect(130, 180, 81, 26));
        input_InstrInNs->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        button_Apply = new QPushButton(BossRc500SystemDialog);
        button_Apply->setObjectName(QString::fromUtf8("button_Apply"));
        button_Apply->setGeometry(QRect(800, 460, 71, 24));
        button_Cancel = new QPushButton(BossRc500SystemDialog);
        button_Cancel->setObjectName(QString::fromUtf8("button_Cancel"));
        button_Cancel->setGeometry(QRect(720, 460, 71, 24));
        QWidget::setTabOrder(general_DisplayContrast, general_DisplayMode);
        QWidget::setTabOrder(general_DisplayMode, general_UndoRedo);
        QWidget::setTabOrder(general_UndoRedo, pref_Pedal1Pref);
        QWidget::setTabOrder(pref_Pedal1Pref, pref_Pedal2Pref);
        QWidget::setTabOrder(pref_Pedal2Pref, pref_Pedal3Pref);
        QWidget::setTabOrder(pref_Pedal3Pref, pref_Ctl1Pref);
        QWidget::setTabOrder(pref_Ctl1Pref, pref_Ctl2Pref);
        QWidget::setTabOrder(pref_Ctl2Pref, pref_ExpPref);
        QWidget::setTabOrder(pref_ExpPref, midi_RxCtlChannel);
        QWidget::setTabOrder(midi_RxCtlChannel, midi_Omni);
        QWidget::setTabOrder(midi_Omni, midi_RxNoteCh);
        QWidget::setTabOrder(midi_RxNoteCh, midi_TxChannel);
        QWidget::setTabOrder(midi_TxChannel, midi_SyncClock);
        QWidget::setTabOrder(midi_SyncClock, midi_ClockOut);
        QWidget::setTabOrder(midi_ClockOut, midi_SyncClock_2);
        QWidget::setTabOrder(midi_SyncClock_2, midi_PcOut);
        QWidget::setTabOrder(midi_PcOut, midi_MidiThru);
        QWidget::setTabOrder(midi_MidiThru, midi_UsbThru);
        QWidget::setTabOrder(midi_UsbThru, extent_Extent);
        QWidget::setTabOrder(extent_Extent, extent_Extent1Min);
        QWidget::setTabOrder(extent_Extent1Min, extent_Extent1Max);
        QWidget::setTabOrder(extent_Extent1Max, extent_Extent2Min);
        QWidget::setTabOrder(extent_Extent2Min, extent_Extent2Max);
        QWidget::setTabOrder(extent_Extent2Max, extent_Extent3Min);
        QWidget::setTabOrder(extent_Extent3Min, extent_Extent3Max);
        QWidget::setTabOrder(extent_Extent3Max, extent_Extent4Min);
        QWidget::setTabOrder(extent_Extent4Min, extent_Extent4Max);
        QWidget::setTabOrder(extent_Extent4Max, extent_Extent5Min);
        QWidget::setTabOrder(extent_Extent5Min, extent_Extent5Max);
        QWidget::setTabOrder(extent_Extent5Max, input_Phantom);
        QWidget::setTabOrder(input_Phantom, input_MicroIn);
        QWidget::setTabOrder(input_MicroIn, input_InstrumentIn);
        QWidget::setTabOrder(input_InstrumentIn, input_Rhythm);
        QWidget::setTabOrder(input_Rhythm, input_MicroInNs);
        QWidget::setTabOrder(input_MicroInNs, input_InstrInNs);
        QWidget::setTabOrder(input_InstrInNs, input_PeakSource);
        QWidget::setTabOrder(input_PeakSource, button_Cancel);
        QWidget::setTabOrder(button_Cancel, button_Apply);

        retranslateUi(BossRc500SystemDialog);

        QMetaObject::connectSlotsByName(BossRc500SystemDialog);
    } // setupUi

    void retranslateUi(QDialog *BossRc500SystemDialog)
    {
        BossRc500SystemDialog->setWindowTitle(QCoreApplication::translate("BossRc500SystemDialog", "Dialog", nullptr));
        gp_General->setTitle(QCoreApplication::translate("BossRc500SystemDialog", "GENERAL", nullptr));
        label_general_DisplayContrast->setText(QCoreApplication::translate("BossRc500SystemDialog", "Display Contrast", nullptr));
        label_general_DisplayMode->setText(QCoreApplication::translate("BossRc500SystemDialog", "Display Mode", nullptr));
        label_general_UndoREdo->setText(QCoreApplication::translate("BossRc500SystemDialog", "Undo/Redo", nullptr));
        gp_Preference->setTitle(QCoreApplication::translate("BossRc500SystemDialog", "PREFERENCE", nullptr));
        label_Pref_Pedal1Pref->setText(QCoreApplication::translate("BossRc500SystemDialog", "Pedal1 Pref.", nullptr));
        label_Pref_Pedal2Pref->setText(QCoreApplication::translate("BossRc500SystemDialog", "Pedal2 Pref.", nullptr));
        label_Pref_Pedal3Pref->setText(QCoreApplication::translate("BossRc500SystemDialog", "Pedal3 Pref.", nullptr));
        label_Pref_Ctl1Pref->setText(QCoreApplication::translate("BossRc500SystemDialog", "Ctl1 Pref.", nullptr));
        label_Pref_Ctl2Pref->setText(QCoreApplication::translate("BossRc500SystemDialog", "Ctl2 Pref.", nullptr));
        label_Pref_ExpPref->setText(QCoreApplication::translate("BossRc500SystemDialog", "Exp. Pref.", nullptr));
        gp_Midi->setTitle(QCoreApplication::translate("BossRc500SystemDialog", "MIDI", nullptr));
        label_midi_RxNoteCh->setText(QCoreApplication::translate("BossRc500SystemDialog", "Rx Note Ch.", nullptr));
        label_midi_TxChannel->setText(QCoreApplication::translate("BossRc500SystemDialog", "Tx Channel", nullptr));
        label_midi_SyncClock->setText(QCoreApplication::translate("BossRc500SystemDialog", "Sync Clock", nullptr));
        label_midi_RxCtlChannel->setText(QCoreApplication::translate("BossRc500SystemDialog", "Rx Ctl Channel", nullptr));
        midi_ClockOut->setText(QCoreApplication::translate("BossRc500SystemDialog", "Clock Out", nullptr));
        label_midi_SyncClock_2->setText(QCoreApplication::translate("BossRc500SystemDialog", "Sync Clock", nullptr));
        midi_PcOut->setText(QCoreApplication::translate("BossRc500SystemDialog", "Pc Out", nullptr));
        label_midi_MidiThru->setText(QCoreApplication::translate("BossRc500SystemDialog", "Midi Thru", nullptr));
        label_midi_UsbThru->setText(QCoreApplication::translate("BossRc500SystemDialog", "Usb Thru", nullptr));
        midi_Omni->setText(QCoreApplication::translate("BossRc500SystemDialog", "Omni", nullptr));
        gp_Extent->setTitle(QCoreApplication::translate("BossRc500SystemDialog", "EXTENT", nullptr));
        label_extent_Extent1->setText(QCoreApplication::translate("BossRc500SystemDialog", "Extent 1", nullptr));
        label_extent_Extent2->setText(QCoreApplication::translate("BossRc500SystemDialog", "Extent 2", nullptr));
        label_extent_Extent3->setText(QCoreApplication::translate("BossRc500SystemDialog", "Extent 3", nullptr));
        label_extent_Extent4->setText(QCoreApplication::translate("BossRc500SystemDialog", "Extent 4", nullptr));
        label_extent_Extent5->setText(QCoreApplication::translate("BossRc500SystemDialog", "Extent 5", nullptr));
        label_extent_Extent->setText(QCoreApplication::translate("BossRc500SystemDialog", "Extent", nullptr));
        label_extent_ExtentMax->setText(QCoreApplication::translate("BossRc500SystemDialog", "Max", nullptr));
        label_extent_ExtentMin->setText(QCoreApplication::translate("BossRc500SystemDialog", "Min", nullptr));
        gp_Input->setTitle(QCoreApplication::translate("BossRc500SystemDialog", "INPUT", nullptr));
        input_Phantom->setText(QCoreApplication::translate("BossRc500SystemDialog", "Phantom", nullptr));
        label_input_MicroIn->setText(QCoreApplication::translate("BossRc500SystemDialog", "Micro In", nullptr));
        label_input_InstrIn->setText(QCoreApplication::translate("BossRc500SystemDialog", "Instrument In", nullptr));
        label_input_Rhythm->setText(QCoreApplication::translate("BossRc500SystemDialog", "Rhythm", nullptr));
        label_input_MicroInNs->setText(QCoreApplication::translate("BossRc500SystemDialog", "Micro In NS", nullptr));
        label_input_PeakSource->setText(QCoreApplication::translate("BossRc500SystemDialog", "Peak Source", nullptr));
        label_input_InstrInNs->setText(QCoreApplication::translate("BossRc500SystemDialog", "Instr. In NS", nullptr));
        button_Apply->setText(QCoreApplication::translate("BossRc500SystemDialog", "Apply", nullptr));
        button_Cancel->setText(QCoreApplication::translate("BossRc500SystemDialog", "Cancel", nullptr));
    } // retranslateUi

};

QT_END_NAMESPACE

#endif // BOSS_2D_RC500_2D_SYSTEMLAOHVG_H
