/********************************************************************************
** Form generated from reading UI file 'Boss-rc500YWKPpy.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef BOSS_2D_RC500YWKPPY_H
#define BOSS_2D_RC500YWKPPY_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QToolButton>

QT_BEGIN_NAMESPACE

class Ui_BossRc500MainDialog
{
public:
    QLabel *label_LoopStation;
    QLabel *label_To;
    QComboBox *cb_CopyFrom;
    QLabel *label_Memory;
    QComboBox *cb_Memory;
    QLabel *label_CopyTo;
    QLabel *label_Boss;
    QComboBox *cb_CopyTo;
    QGroupBox *gp_Track1;
    QCheckBox *track1_Reverse;
    QSlider *track1_Level;
    QLabel *label_track1_Level;
    QCheckBox *track1_LoopFx;
    QCheckBox *track1_OneShot;
    QLabel *label_track1_Pan;
    QComboBox *track1_Pan;
    QComboBox *track1_Stop;
    QLabel *label_track1_Stop;
    QComboBox *track1_Start;
    QLabel *label_track1_Start;
    QComboBox *track1_Measure;
    QLabel *label_track1_Measure;
    QCheckBox *track1_LoopSync;
    QCheckBox *track1_TempoSync;
    QLabel *label_track1_Output;
    QComboBox *track1_Input;
    QComboBox *track1_Output;
    QLabel *label_track1_Input;
    QLabel *label_track1_PlyLevel;
    QGroupBox *gp_Track2;
    QComboBox *track2_Measure;
    QLabel *label_track2_Stop;
    QLabel *label_track2_Output;
    QComboBox *track2_Stop;
    QComboBox *track2_Pan;
    QCheckBox *track2_OneShot;
    QCheckBox *track2_TempoSync;
    QCheckBox *track2_LoopSync;
    QLabel *label_track2_Measure;
    QComboBox *track2_Output;
    QLabel *label_track2_Start;
    QLabel *label_track2_Input;
    QCheckBox *track2_Reverse;
    QComboBox *track2_Start;
    QComboBox *track2_Input;
    QCheckBox *track2_LoopFx;
    QSlider *track2_Level;
    QLabel *label_track2_Level;
    QLabel *label_track2_Pan;
    QLabel *label_track2_PlyLevel;
    QPushButton *button_Copy;
    QGroupBox *gp_Record;
    QLabel *label_record_DubMode;
    QComboBox *record_DubMode;
    QComboBox *record_Quantize;
    QLabel *label_record_Quantize;
    QComboBox *record_RecordAction;
    QLabel *label_record_RecordAction;
    QCheckBox *record_AutoRecord;
    QLabel *label_record_AutoRecordSource;
    QComboBox *record_AutoRecordSource;
    QLabel *label_record_Input_3;
    QLabel *label_record_LoopLength;
    QComboBox *record_LoopLength;
    QSpinBox *record_AutoRecordSensitivity;
    QGroupBox *gp_Play;
    QLabel *label_play_PlayMode;
    QComboBox *play_PlayMode;
    QLabel *label_play_Level;
    QComboBox *play_SingleChange;
    QLabel *label_play_SingleChange;
    QLabel *label_play_AllStart;
    QComboBox *play_FadeTime;
    QComboBox *play_AllStart;
    QLabel *label_play_FadeTime;
    QLabel *label_play_TrackChain;
    QComboBox *play_TrackChain;
    QSpinBox *play_Level;
    QLabel *label_play_Tempo;
    QDoubleSpinBox *play_Tempo;
    QGroupBox *gp_Rhythm;
    QSlider *rhythm_Level;
    QLabel *label_rhythm_Level;
    QLabel *label_rhythm_Reverb;
    QSlider *rhythm_Reverb;
    QComboBox *rhythm_Pattern;
    QLabel *label_rhythm_Pattern;
    QComboBox *rhythm_Variation;
    QLabel *label_rhythm_Variation;
    QComboBox *rhythm_VarChange;
    QLabel *label_rhythm_VarChange;
    QLabel *label_rhythm_Kit;
    QComboBox *rhythm_Kit;
    QLabel *label_rhythm_Beat;
    QComboBox *rhythm_Beat;
    QLabel *label_rhythm_Start;
    QComboBox *rhythm_Start;
    QLabel *label_rhythm_Stop;
    QComboBox *rhythm_Stop;
    QComboBox *rhythm_RecCount;
    QLabel *label_rhythm_RecCount;
    QLabel *label_rhythm_PlayCount;
    QComboBox *rhythm_PlayCount;
    QCheckBox *rhythm_Fill;
    QCheckBox *rhythm_Part1;
    QCheckBox *rhythm_Part2;
    QCheckBox *rhythm_Part3;
    QCheckBox *rhythm_Part4;
    QLabel *label_rhythm_Part;
    QLabel *label_rhythm_Tone;
    QSlider *rhythm_ToneLow;
    QSlider *rhythm_ToneHigh;
    QGroupBox *gb_LoopFx;
    QLabel *label_loopFx_Type;
    QComboBox *loopFx_Type;
    QLabel *label_loopFx_ScatLen;
    QComboBox *loopFx_ScatLen;
    QComboBox *loopFx_ReptLen;
    QLabel *label_loopFx_ReptLen;
    QLabel *label_loopFx_Shift;
    QComboBox *loopFx_Shift;
    QLabel *label_loopFx_Flick;
    QSpinBox *loopFx_Flick;
    QCheckBox *loopFx_Sw;
    QPushButton *button_Edit;
    QGroupBox *gb_Control;
    QLabel *label_control_Pedal1;
    QComboBox *control_Pedal1;
    QLabel *label_control_Pedal2;
    QComboBox *control_Pedal2;
    QComboBox *control_Pedal3;
    QLabel *label_control_Pedal3;
    QLabel *label_control_Control1;
    QComboBox *control_Control1;
    QLabel *label_control_Control2;
    QComboBox *control_Control2;
    QLabel *label_control_Expression;
    QComboBox *control_Expression;
    QToolButton *toolButton;

    void setupUi(QDialog *BossRc500MainDialog)
    {
        if (BossRc500MainDialog->objectName().isEmpty())
            BossRc500MainDialog->setObjectName(QString::fromUtf8("BossRc500MainDialog"));
        BossRc500MainDialog->resize(1128, 712);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(170, 49, 45, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        BossRc500MainDialog->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("Bitstream Vera Sans"));
        font.setBold(true);
        font.setWeight(QFont::DemiBold);
        BossRc500MainDialog->setFont(font);
        label_LoopStation = new QLabel(BossRc500MainDialog);
        label_LoopStation->setObjectName(QString::fromUtf8("label_LoopStation"));
        label_LoopStation->setGeometry(QRect(790, 0, 341, 31));
        label_LoopStation->setPixmap(QPixmap(QString::fromUtf8("resources/images/loop station.png")));
        label_LoopStation->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_To = new QLabel(BossRc500MainDialog);
        label_To->setObjectName(QString::fromUtf8("label_To"));
        label_To->setGeometry(QRect(960, 50, 21, 21));
        cb_CopyFrom = new QComboBox(BossRc500MainDialog);
        cb_CopyFrom->setObjectName(QString::fromUtf8("cb_CopyFrom"));
        cb_CopyFrom->setGeometry(QRect(900, 50, 51, 25));
        label_Memory = new QLabel(BossRc500MainDialog);
        label_Memory->setObjectName(QString::fromUtf8("label_Memory"));
        label_Memory->setGeometry(QRect(180, 50, 61, 21));
        cb_Memory = new QComboBox(BossRc500MainDialog);
        cb_Memory->setObjectName(QString::fromUtf8("cb_Memory"));
        cb_Memory->setGeometry(QRect(250, 50, 221, 25));
        label_CopyTo = new QLabel(BossRc500MainDialog);
        label_CopyTo->setObjectName(QString::fromUtf8("label_CopyTo"));
        label_CopyTo->setGeometry(QRect(850, 50, 41, 21));
        label_Boss = new QLabel(BossRc500MainDialog);
        label_Boss->setObjectName(QString::fromUtf8("label_Boss"));
        label_Boss->setGeometry(QRect(0, 0, 190, 40));
        label_Boss->setPixmap(QPixmap(QString::fromUtf8("resources/images/boss.png")));
        cb_CopyTo = new QComboBox(BossRc500MainDialog);
        cb_CopyTo->setObjectName(QString::fromUtf8("cb_CopyTo"));
        cb_CopyTo->setGeometry(QRect(990, 50, 51, 25));
        gp_Track1 = new QGroupBox(BossRc500MainDialog);
        gp_Track1->setObjectName(QString::fromUtf8("gp_Track1"));
        gp_Track1->setGeometry(QRect(10, 90, 341, 341));
        track1_Reverse = new QCheckBox(gp_Track1);
        track1_Reverse->setObjectName(QString::fromUtf8("track1_Reverse"));
        track1_Reverse->setGeometry(QRect(110, 30, 91, 23));
        track1_Reverse->setLayoutDirection(Qt::RightToLeft);
        track1_Level = new QSlider(gp_Track1);
        track1_Level->setObjectName(QString::fromUtf8("track1_Level"));
        track1_Level->setGeometry(QRect(10, 30, 41, 251));
        track1_Level->setMaximum(200);
        track1_Level->setOrientation(Qt::Vertical);
        track1_Level->setTickPosition(QSlider::TicksBothSides);
        label_track1_Level = new QLabel(gp_Track1);
        label_track1_Level->setObjectName(QString::fromUtf8("label_track1_Level"));
        label_track1_Level->setGeometry(QRect(10, 290, 41, 21));
        track1_LoopFx = new QCheckBox(gp_Track1);
        track1_LoopFx->setObjectName(QString::fromUtf8("track1_LoopFx"));
        track1_LoopFx->setGeometry(QRect(120, 50, 81, 23));
        track1_LoopFx->setLayoutDirection(Qt::RightToLeft);
        track1_LoopFx->setAutoFillBackground(false);
        track1_OneShot = new QCheckBox(gp_Track1);
        track1_OneShot->setObjectName(QString::fromUtf8("track1_OneShot"));
        track1_OneShot->setGeometry(QRect(110, 70, 91, 23));
        track1_OneShot->setLayoutDirection(Qt::RightToLeft);
        label_track1_Pan = new QLabel(gp_Track1);
        label_track1_Pan->setObjectName(QString::fromUtf8("label_track1_Pan"));
        label_track1_Pan->setGeometry(QRect(90, 100, 91, 21));
        track1_Pan = new QComboBox(gp_Track1);
        track1_Pan->setObjectName(QString::fromUtf8("track1_Pan"));
        track1_Pan->setGeometry(QRect(190, 100, 91, 25));
        track1_Stop = new QComboBox(gp_Track1);
        track1_Stop->setObjectName(QString::fromUtf8("track1_Stop"));
        track1_Stop->setGeometry(QRect(190, 160, 121, 25));
        label_track1_Stop = new QLabel(gp_Track1);
        label_track1_Stop->setObjectName(QString::fromUtf8("label_track1_Stop"));
        label_track1_Stop->setGeometry(QRect(90, 160, 91, 21));
        track1_Start = new QComboBox(gp_Track1);
        track1_Start->setObjectName(QString::fromUtf8("track1_Start"));
        track1_Start->setGeometry(QRect(190, 130, 121, 25));
        label_track1_Start = new QLabel(gp_Track1);
        label_track1_Start->setObjectName(QString::fromUtf8("label_track1_Start"));
        label_track1_Start->setGeometry(QRect(90, 130, 91, 21));
        track1_Measure = new QComboBox(gp_Track1);
        track1_Measure->setObjectName(QString::fromUtf8("track1_Measure"));
        track1_Measure->setGeometry(QRect(190, 190, 141, 25));
        label_track1_Measure = new QLabel(gp_Track1);
        label_track1_Measure->setObjectName(QString::fromUtf8("label_track1_Measure"));
        label_track1_Measure->setGeometry(QRect(90, 190, 91, 21));
        track1_LoopSync = new QCheckBox(gp_Track1);
        track1_LoopSync->setObjectName(QString::fromUtf8("track1_LoopSync"));
        track1_LoopSync->setGeometry(QRect(80, 220, 121, 21));
        track1_LoopSync->setLayoutDirection(Qt::RightToLeft);
        track1_TempoSync = new QCheckBox(gp_Track1);
        track1_TempoSync->setObjectName(QString::fromUtf8("track1_TempoSync"));
        track1_TempoSync->setGeometry(QRect(70, 240, 131, 23));
        track1_TempoSync->setLayoutDirection(Qt::RightToLeft);
        label_track1_Output = new QLabel(gp_Track1);
        label_track1_Output->setObjectName(QString::fromUtf8("label_track1_Output"));
        label_track1_Output->setGeometry(QRect(90, 300, 71, 21));
        track1_Input = new QComboBox(gp_Track1);
        track1_Input->setObjectName(QString::fromUtf8("track1_Input"));
        track1_Input->setGeometry(QRect(190, 270, 121, 25));
        track1_Output = new QComboBox(gp_Track1);
        track1_Output->setObjectName(QString::fromUtf8("track1_Output"));
        track1_Output->setGeometry(QRect(190, 300, 121, 25));
        label_track1_Input = new QLabel(gp_Track1);
        label_track1_Input->setObjectName(QString::fromUtf8("label_track1_Input"));
        label_track1_Input->setGeometry(QRect(90, 270, 71, 21));
        label_track1_PlyLevel = new QLabel(gp_Track1);
        label_track1_PlyLevel->setObjectName(QString::fromUtf8("label_track1_PlyLevel"));
        label_track1_PlyLevel->setGeometry(QRect(10, 310, 41, 21));
        label_track1_PlyLevel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        gp_Track2 = new QGroupBox(BossRc500MainDialog);
        gp_Track2->setObjectName(QString::fromUtf8("gp_Track2"));
        gp_Track2->setGeometry(QRect(360, 90, 341, 341));
        track2_Measure = new QComboBox(gp_Track2);
        track2_Measure->setObjectName(QString::fromUtf8("track2_Measure"));
        track2_Measure->setGeometry(QRect(190, 190, 141, 25));
        label_track2_Stop = new QLabel(gp_Track2);
        label_track2_Stop->setObjectName(QString::fromUtf8("label_track2_Stop"));
        label_track2_Stop->setGeometry(QRect(90, 160, 91, 21));
        label_track2_Output = new QLabel(gp_Track2);
        label_track2_Output->setObjectName(QString::fromUtf8("label_track2_Output"));
        label_track2_Output->setGeometry(QRect(90, 300, 91, 21));
        track2_Stop = new QComboBox(gp_Track2);
        track2_Stop->setObjectName(QString::fromUtf8("track2_Stop"));
        track2_Stop->setGeometry(QRect(190, 160, 121, 25));
        track2_Pan = new QComboBox(gp_Track2);
        track2_Pan->setObjectName(QString::fromUtf8("track2_Pan"));
        track2_Pan->setGeometry(QRect(190, 100, 91, 25));
        track2_OneShot = new QCheckBox(gp_Track2);
        track2_OneShot->setObjectName(QString::fromUtf8("track2_OneShot"));
        track2_OneShot->setGeometry(QRect(110, 70, 91, 23));
        track2_OneShot->setLayoutDirection(Qt::RightToLeft);
        track2_TempoSync = new QCheckBox(gp_Track2);
        track2_TempoSync->setObjectName(QString::fromUtf8("track2_TempoSync"));
        track2_TempoSync->setGeometry(QRect(80, 240, 121, 23));
        track2_TempoSync->setLayoutDirection(Qt::RightToLeft);
        track2_LoopSync = new QCheckBox(gp_Track2);
        track2_LoopSync->setObjectName(QString::fromUtf8("track2_LoopSync"));
        track2_LoopSync->setGeometry(QRect(80, 220, 121, 21));
        track2_LoopSync->setLayoutDirection(Qt::RightToLeft);
        label_track2_Measure = new QLabel(gp_Track2);
        label_track2_Measure->setObjectName(QString::fromUtf8("label_track2_Measure"));
        label_track2_Measure->setGeometry(QRect(90, 190, 91, 21));
        track2_Output = new QComboBox(gp_Track2);
        track2_Output->setObjectName(QString::fromUtf8("track2_Output"));
        track2_Output->setGeometry(QRect(190, 300, 121, 25));
        label_track2_Start = new QLabel(gp_Track2);
        label_track2_Start->setObjectName(QString::fromUtf8("label_track2_Start"));
        label_track2_Start->setGeometry(QRect(90, 130, 91, 21));
        label_track2_Input = new QLabel(gp_Track2);
        label_track2_Input->setObjectName(QString::fromUtf8("label_track2_Input"));
        label_track2_Input->setGeometry(QRect(90, 270, 91, 21));
        track2_Reverse = new QCheckBox(gp_Track2);
        track2_Reverse->setObjectName(QString::fromUtf8("track2_Reverse"));
        track2_Reverse->setGeometry(QRect(120, 30, 81, 23));
        track2_Reverse->setLayoutDirection(Qt::RightToLeft);
        track2_Start = new QComboBox(gp_Track2);
        track2_Start->setObjectName(QString::fromUtf8("track2_Start"));
        track2_Start->setGeometry(QRect(190, 130, 121, 25));
        track2_Input = new QComboBox(gp_Track2);
        track2_Input->setObjectName(QString::fromUtf8("track2_Input"));
        track2_Input->setGeometry(QRect(190, 270, 121, 25));
        track2_LoopFx = new QCheckBox(gp_Track2);
        track2_LoopFx->setObjectName(QString::fromUtf8("track2_LoopFx"));
        track2_LoopFx->setGeometry(QRect(120, 50, 81, 23));
        track2_LoopFx->setLayoutDirection(Qt::RightToLeft);
        track2_LoopFx->setAutoFillBackground(false);
        track2_Level = new QSlider(gp_Track2);
        track2_Level->setObjectName(QString::fromUtf8("track2_Level"));
        track2_Level->setGeometry(QRect(10, 30, 41, 251));
        track2_Level->setMaximum(200);
        track2_Level->setOrientation(Qt::Vertical);
        track2_Level->setTickPosition(QSlider::TicksBothSides);
        label_track2_Level = new QLabel(gp_Track2);
        label_track2_Level->setObjectName(QString::fromUtf8("label_track2_Level"));
        label_track2_Level->setGeometry(QRect(10, 290, 41, 21));
        label_track2_Pan = new QLabel(gp_Track2);
        label_track2_Pan->setObjectName(QString::fromUtf8("label_track2_Pan"));
        label_track2_Pan->setGeometry(QRect(90, 100, 91, 21));
        label_track2_PlyLevel = new QLabel(gp_Track2);
        label_track2_PlyLevel->setObjectName(QString::fromUtf8("label_track2_PlyLevel"));
        label_track2_PlyLevel->setGeometry(QRect(10, 310, 41, 21));
        label_track2_PlyLevel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        button_Copy = new QPushButton(BossRc500MainDialog);
        button_Copy->setObjectName(QString::fromUtf8("button_Copy"));
        button_Copy->setGeometry(QRect(1060, 50, 51, 24));
        gp_Record = new QGroupBox(BossRc500MainDialog);
        gp_Record->setObjectName(QString::fromUtf8("gp_Record"));
        gp_Record->setGeometry(QRect(10, 440, 301, 241));
        label_record_DubMode = new QLabel(gp_Record);
        label_record_DubMode->setObjectName(QString::fromUtf8("label_record_DubMode"));
        label_record_DubMode->setGeometry(QRect(10, 30, 121, 21));
        record_DubMode = new QComboBox(gp_Record);
        record_DubMode->setObjectName(QString::fromUtf8("record_DubMode"));
        record_DubMode->setGeometry(QRect(170, 30, 121, 25));
        record_Quantize = new QComboBox(gp_Record);
        record_Quantize->setObjectName(QString::fromUtf8("record_Quantize"));
        record_Quantize->setGeometry(QRect(170, 90, 121, 25));
        label_record_Quantize = new QLabel(gp_Record);
        label_record_Quantize->setObjectName(QString::fromUtf8("label_record_Quantize"));
        label_record_Quantize->setGeometry(QRect(10, 90, 121, 21));
        record_RecordAction = new QComboBox(gp_Record);
        record_RecordAction->setObjectName(QString::fromUtf8("record_RecordAction"));
        record_RecordAction->setGeometry(QRect(170, 60, 121, 25));
        label_record_RecordAction = new QLabel(gp_Record);
        label_record_RecordAction->setObjectName(QString::fromUtf8("label_record_RecordAction"));
        label_record_RecordAction->setGeometry(QRect(10, 60, 121, 21));
        record_AutoRecord = new QCheckBox(gp_Record);
        record_AutoRecord->setObjectName(QString::fromUtf8("record_AutoRecord"));
        record_AutoRecord->setGeometry(QRect(60, 120, 121, 21));
        record_AutoRecord->setLayoutDirection(Qt::RightToLeft);
        label_record_AutoRecordSource = new QLabel(gp_Record);
        label_record_AutoRecordSource->setObjectName(QString::fromUtf8("label_record_AutoRecordSource"));
        label_record_AutoRecordSource->setGeometry(QRect(10, 180, 151, 21));
        record_AutoRecordSource = new QComboBox(gp_Record);
        record_AutoRecordSource->setObjectName(QString::fromUtf8("record_AutoRecordSource"));
        record_AutoRecordSource->setGeometry(QRect(170, 180, 121, 25));
        label_record_Input_3 = new QLabel(gp_Record);
        label_record_Input_3->setObjectName(QString::fromUtf8("label_record_Input_3"));
        label_record_Input_3->setGeometry(QRect(10, 150, 161, 21));
        label_record_LoopLength = new QLabel(gp_Record);
        label_record_LoopLength->setObjectName(QString::fromUtf8("label_record_LoopLength"));
        label_record_LoopLength->setGeometry(QRect(10, 210, 141, 21));
        record_LoopLength = new QComboBox(gp_Record);
        record_LoopLength->setObjectName(QString::fromUtf8("record_LoopLength"));
        record_LoopLength->setGeometry(QRect(170, 210, 121, 25));
        record_AutoRecordSensitivity = new QSpinBox(gp_Record);
        record_AutoRecordSensitivity->setObjectName(QString::fromUtf8("record_AutoRecordSensitivity"));
        record_AutoRecordSensitivity->setGeometry(QRect(170, 150, 71, 24));
        record_AutoRecordSensitivity->setLayoutDirection(Qt::LeftToRight);
        record_AutoRecordSensitivity->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        record_AutoRecordSensitivity->setMaximum(100);
        gp_Play = new QGroupBox(BossRc500MainDialog);
        gp_Play->setObjectName(QString::fromUtf8("gp_Play"));
        gp_Play->setGeometry(QRect(320, 440, 291, 241));
        label_play_PlayMode = new QLabel(gp_Play);
        label_play_PlayMode->setObjectName(QString::fromUtf8("label_play_PlayMode"));
        label_play_PlayMode->setGeometry(QRect(10, 60, 121, 21));
        play_PlayMode = new QComboBox(gp_Play);
        play_PlayMode->setObjectName(QString::fromUtf8("play_PlayMode"));
        play_PlayMode->setGeometry(QRect(160, 60, 121, 25));
        label_play_Level = new QLabel(gp_Play);
        label_play_Level->setObjectName(QString::fromUtf8("label_play_Level"));
        label_play_Level->setGeometry(QRect(10, 120, 141, 21));
        play_SingleChange = new QComboBox(gp_Play);
        play_SingleChange->setObjectName(QString::fromUtf8("play_SingleChange"));
        play_SingleChange->setGeometry(QRect(160, 90, 121, 25));
        label_play_SingleChange = new QLabel(gp_Play);
        label_play_SingleChange->setObjectName(QString::fromUtf8("label_play_SingleChange"));
        label_play_SingleChange->setGeometry(QRect(10, 90, 121, 21));
        label_play_AllStart = new QLabel(gp_Play);
        label_play_AllStart->setObjectName(QString::fromUtf8("label_play_AllStart"));
        label_play_AllStart->setGeometry(QRect(10, 180, 141, 21));
        play_FadeTime = new QComboBox(gp_Play);
        play_FadeTime->setObjectName(QString::fromUtf8("play_FadeTime"));
        play_FadeTime->setGeometry(QRect(160, 150, 121, 25));
        play_AllStart = new QComboBox(gp_Play);
        play_AllStart->setObjectName(QString::fromUtf8("play_AllStart"));
        play_AllStart->setGeometry(QRect(160, 180, 121, 25));
        label_play_FadeTime = new QLabel(gp_Play);
        label_play_FadeTime->setObjectName(QString::fromUtf8("label_play_FadeTime"));
        label_play_FadeTime->setGeometry(QRect(10, 150, 131, 21));
        label_play_TrackChain = new QLabel(gp_Play);
        label_play_TrackChain->setObjectName(QString::fromUtf8("label_play_TrackChain"));
        label_play_TrackChain->setGeometry(QRect(10, 210, 141, 21));
        play_TrackChain = new QComboBox(gp_Play);
        play_TrackChain->setObjectName(QString::fromUtf8("play_TrackChain"));
        play_TrackChain->setGeometry(QRect(160, 210, 121, 25));
        play_Level = new QSpinBox(gp_Play);
        play_Level->setObjectName(QString::fromUtf8("play_Level"));
        play_Level->setGeometry(QRect(160, 120, 71, 24));
        play_Level->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        play_Level->setMaximum(100);
        label_play_Tempo = new QLabel(gp_Play);
        label_play_Tempo->setObjectName(QString::fromUtf8("label_play_Tempo"));
        label_play_Tempo->setGeometry(QRect(10, 30, 141, 21));
        play_Tempo = new QDoubleSpinBox(gp_Play);
        play_Tempo->setObjectName(QString::fromUtf8("play_Tempo"));
        play_Tempo->setGeometry(QRect(160, 30, 91, 24));
        play_Tempo->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        play_Tempo->setDecimals(1);
        play_Tempo->setMinimum(40.000000000000000);
        play_Tempo->setMaximum(240.000000000000000);
        gp_Rhythm = new QGroupBox(BossRc500MainDialog);
        gp_Rhythm->setObjectName(QString::fromUtf8("gp_Rhythm"));
        gp_Rhythm->setGeometry(QRect(710, 90, 391, 391));
        rhythm_Level = new QSlider(gp_Rhythm);
        rhythm_Level->setObjectName(QString::fromUtf8("rhythm_Level"));
        rhythm_Level->setGeometry(QRect(10, 30, 41, 181));
        rhythm_Level->setMaximum(200);
        rhythm_Level->setOrientation(Qt::Vertical);
        rhythm_Level->setTickPosition(QSlider::TicksBothSides);
        label_rhythm_Level = new QLabel(gp_Rhythm);
        label_rhythm_Level->setObjectName(QString::fromUtf8("label_rhythm_Level"));
        label_rhythm_Level->setGeometry(QRect(10, 220, 41, 21));
        label_rhythm_Reverb = new QLabel(gp_Rhythm);
        label_rhythm_Reverb->setObjectName(QString::fromUtf8("label_rhythm_Reverb"));
        label_rhythm_Reverb->setGeometry(QRect(70, 220, 51, 21));
        rhythm_Reverb = new QSlider(gp_Rhythm);
        rhythm_Reverb->setObjectName(QString::fromUtf8("rhythm_Reverb"));
        rhythm_Reverb->setGeometry(QRect(70, 30, 41, 181));
        rhythm_Reverb->setMaximum(200);
        rhythm_Reverb->setOrientation(Qt::Vertical);
        rhythm_Reverb->setTickPosition(QSlider::TicksBothSides);
        rhythm_Pattern = new QComboBox(gp_Rhythm);
        rhythm_Pattern->setObjectName(QString::fromUtf8("rhythm_Pattern"));
        rhythm_Pattern->setGeometry(QRect(230, 30, 151, 25));
        label_rhythm_Pattern = new QLabel(gp_Rhythm);
        label_rhythm_Pattern->setObjectName(QString::fromUtf8("label_rhythm_Pattern"));
        label_rhythm_Pattern->setGeometry(QRect(130, 30, 91, 21));
        rhythm_Variation = new QComboBox(gp_Rhythm);
        rhythm_Variation->setObjectName(QString::fromUtf8("rhythm_Variation"));
        rhythm_Variation->setGeometry(QRect(230, 60, 41, 25));
        label_rhythm_Variation = new QLabel(gp_Rhythm);
        label_rhythm_Variation->setObjectName(QString::fromUtf8("label_rhythm_Variation"));
        label_rhythm_Variation->setGeometry(QRect(130, 60, 91, 21));
        rhythm_VarChange = new QComboBox(gp_Rhythm);
        rhythm_VarChange->setObjectName(QString::fromUtf8("rhythm_VarChange"));
        rhythm_VarChange->setGeometry(QRect(230, 90, 151, 25));
        label_rhythm_VarChange = new QLabel(gp_Rhythm);
        label_rhythm_VarChange->setObjectName(QString::fromUtf8("label_rhythm_VarChange"));
        label_rhythm_VarChange->setGeometry(QRect(130, 90, 91, 21));
        label_rhythm_Kit = new QLabel(gp_Rhythm);
        label_rhythm_Kit->setObjectName(QString::fromUtf8("label_rhythm_Kit"));
        label_rhythm_Kit->setGeometry(QRect(130, 120, 91, 21));
        rhythm_Kit = new QComboBox(gp_Rhythm);
        rhythm_Kit->setObjectName(QString::fromUtf8("rhythm_Kit"));
        rhythm_Kit->setGeometry(QRect(230, 120, 151, 25));
        label_rhythm_Beat = new QLabel(gp_Rhythm);
        label_rhythm_Beat->setObjectName(QString::fromUtf8("label_rhythm_Beat"));
        label_rhythm_Beat->setGeometry(QRect(130, 150, 91, 21));
        rhythm_Beat = new QComboBox(gp_Rhythm);
        rhythm_Beat->setObjectName(QString::fromUtf8("rhythm_Beat"));
        rhythm_Beat->setGeometry(QRect(230, 150, 151, 25));
        label_rhythm_Start = new QLabel(gp_Rhythm);
        label_rhythm_Start->setObjectName(QString::fromUtf8("label_rhythm_Start"));
        label_rhythm_Start->setGeometry(QRect(130, 180, 91, 21));
        rhythm_Start = new QComboBox(gp_Rhythm);
        rhythm_Start->setObjectName(QString::fromUtf8("rhythm_Start"));
        rhythm_Start->setGeometry(QRect(230, 180, 151, 25));
        label_rhythm_Stop = new QLabel(gp_Rhythm);
        label_rhythm_Stop->setObjectName(QString::fromUtf8("label_rhythm_Stop"));
        label_rhythm_Stop->setGeometry(QRect(130, 210, 91, 21));
        rhythm_Stop = new QComboBox(gp_Rhythm);
        rhythm_Stop->setObjectName(QString::fromUtf8("rhythm_Stop"));
        rhythm_Stop->setGeometry(QRect(230, 210, 151, 25));
        rhythm_RecCount = new QComboBox(gp_Rhythm);
        rhythm_RecCount->setObjectName(QString::fromUtf8("rhythm_RecCount"));
        rhythm_RecCount->setGeometry(QRect(230, 240, 151, 25));
        label_rhythm_RecCount = new QLabel(gp_Rhythm);
        label_rhythm_RecCount->setObjectName(QString::fromUtf8("label_rhythm_RecCount"));
        label_rhythm_RecCount->setGeometry(QRect(130, 240, 91, 21));
        label_rhythm_PlayCount = new QLabel(gp_Rhythm);
        label_rhythm_PlayCount->setObjectName(QString::fromUtf8("label_rhythm_PlayCount"));
        label_rhythm_PlayCount->setGeometry(QRect(130, 270, 91, 21));
        rhythm_PlayCount = new QComboBox(gp_Rhythm);
        rhythm_PlayCount->setObjectName(QString::fromUtf8("rhythm_PlayCount"));
        rhythm_PlayCount->setGeometry(QRect(230, 270, 151, 25));
        rhythm_Fill = new QCheckBox(gp_Rhythm);
        rhythm_Fill->setObjectName(QString::fromUtf8("rhythm_Fill"));
        rhythm_Fill->setGeometry(QRect(130, 300, 111, 23));
        rhythm_Fill->setLayoutDirection(Qt::RightToLeft);
        rhythm_Part1 = new QCheckBox(gp_Rhythm);
        rhythm_Part1->setObjectName(QString::fromUtf8("rhythm_Part1"));
        rhythm_Part1->setGeometry(QRect(230, 320, 31, 23));
        rhythm_Part1->setLayoutDirection(Qt::RightToLeft);
        rhythm_Part2 = new QCheckBox(gp_Rhythm);
        rhythm_Part2->setObjectName(QString::fromUtf8("rhythm_Part2"));
        rhythm_Part2->setGeometry(QRect(270, 320, 31, 23));
        rhythm_Part2->setLayoutDirection(Qt::RightToLeft);
        rhythm_Part3 = new QCheckBox(gp_Rhythm);
        rhythm_Part3->setObjectName(QString::fromUtf8("rhythm_Part3"));
        rhythm_Part3->setGeometry(QRect(310, 320, 31, 23));
        rhythm_Part3->setLayoutDirection(Qt::RightToLeft);
        rhythm_Part4 = new QCheckBox(gp_Rhythm);
        rhythm_Part4->setObjectName(QString::fromUtf8("rhythm_Part4"));
        rhythm_Part4->setGeometry(QRect(350, 320, 31, 23));
        rhythm_Part4->setLayoutDirection(Qt::RightToLeft);
        label_rhythm_Part = new QLabel(gp_Rhythm);
        label_rhythm_Part->setObjectName(QString::fromUtf8("label_rhythm_Part"));
        label_rhythm_Part->setGeometry(QRect(130, 320, 91, 21));
        label_rhythm_Tone = new QLabel(gp_Rhythm);
        label_rhythm_Tone->setObjectName(QString::fromUtf8("label_rhythm_Tone"));
        label_rhythm_Tone->setGeometry(QRect(20, 360, 111, 21));
        rhythm_ToneLow = new QSlider(gp_Rhythm);
        rhythm_ToneLow->setObjectName(QString::fromUtf8("rhythm_ToneLow"));
        rhythm_ToneLow->setGeometry(QRect(10, 250, 51, 111));
        rhythm_ToneLow->setMinimum(-10);
        rhythm_ToneLow->setMaximum(10);
        rhythm_ToneLow->setPageStep(2);
        rhythm_ToneLow->setOrientation(Qt::Vertical);
        rhythm_ToneLow->setTickPosition(QSlider::TicksBothSides);
        rhythm_ToneHigh = new QSlider(gp_Rhythm);
        rhythm_ToneHigh->setObjectName(QString::fromUtf8("rhythm_ToneHigh"));
        rhythm_ToneHigh->setGeometry(QRect(70, 250, 51, 111));
        rhythm_ToneHigh->setMinimum(-10);
        rhythm_ToneHigh->setMaximum(10);
        rhythm_ToneHigh->setPageStep(2);
        rhythm_ToneHigh->setTracking(false);
        rhythm_ToneHigh->setOrientation(Qt::Vertical);
        rhythm_ToneHigh->setTickPosition(QSlider::TicksBothSides);
        gb_LoopFx = new QGroupBox(BossRc500MainDialog);
        gb_LoopFx->setObjectName(QString::fromUtf8("gb_LoopFx"));
        gb_LoopFx->setGeometry(QRect(630, 490, 231, 211));
        label_loopFx_Type = new QLabel(gb_LoopFx);
        label_loopFx_Type->setObjectName(QString::fromUtf8("label_loopFx_Type"));
        label_loopFx_Type->setGeometry(QRect(10, 60, 71, 21));
        loopFx_Type = new QComboBox(gb_LoopFx);
        loopFx_Type->setObjectName(QString::fromUtf8("loopFx_Type"));
        loopFx_Type->setGeometry(QRect(80, 60, 141, 25));
        label_loopFx_ScatLen = new QLabel(gb_LoopFx);
        label_loopFx_ScatLen->setObjectName(QString::fromUtf8("label_loopFx_ScatLen"));
        label_loopFx_ScatLen->setGeometry(QRect(10, 90, 71, 21));
        loopFx_ScatLen = new QComboBox(gb_LoopFx);
        loopFx_ScatLen->setObjectName(QString::fromUtf8("loopFx_ScatLen"));
        loopFx_ScatLen->setGeometry(QRect(80, 90, 141, 25));
        loopFx_ReptLen = new QComboBox(gb_LoopFx);
        loopFx_ReptLen->setObjectName(QString::fromUtf8("loopFx_ReptLen"));
        loopFx_ReptLen->setGeometry(QRect(80, 120, 141, 25));
        label_loopFx_ReptLen = new QLabel(gb_LoopFx);
        label_loopFx_ReptLen->setObjectName(QString::fromUtf8("label_loopFx_ReptLen"));
        label_loopFx_ReptLen->setGeometry(QRect(10, 120, 71, 21));
        label_loopFx_Shift = new QLabel(gb_LoopFx);
        label_loopFx_Shift->setObjectName(QString::fromUtf8("label_loopFx_Shift"));
        label_loopFx_Shift->setGeometry(QRect(10, 150, 71, 21));
        loopFx_Shift = new QComboBox(gb_LoopFx);
        loopFx_Shift->setObjectName(QString::fromUtf8("loopFx_Shift"));
        loopFx_Shift->setGeometry(QRect(80, 150, 141, 25));
        label_loopFx_Flick = new QLabel(gb_LoopFx);
        label_loopFx_Flick->setObjectName(QString::fromUtf8("label_loopFx_Flick"));
        label_loopFx_Flick->setGeometry(QRect(10, 180, 61, 21));
        loopFx_Flick = new QSpinBox(gb_LoopFx);
        loopFx_Flick->setObjectName(QString::fromUtf8("loopFx_Flick"));
        loopFx_Flick->setGeometry(QRect(80, 180, 61, 24));
        loopFx_Flick->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        loopFx_Flick->setMaximum(100);
        loopFx_Sw = new QCheckBox(gb_LoopFx);
        loopFx_Sw->setObjectName(QString::fromUtf8("loopFx_Sw"));
        loopFx_Sw->setGeometry(QRect(10, 30, 81, 21));
        loopFx_Sw->setLayoutDirection(Qt::RightToLeft);
        button_Edit = new QPushButton(BossRc500MainDialog);
        button_Edit->setObjectName(QString::fromUtf8("button_Edit"));
        button_Edit->setGeometry(QRect(480, 50, 51, 24));
        gb_Control = new QGroupBox(BossRc500MainDialog);
        gb_Control->setObjectName(QString::fromUtf8("gb_Control"));
        gb_Control->setGeometry(QRect(870, 490, 251, 211));
        label_control_Pedal1 = new QLabel(gb_Control);
        label_control_Pedal1->setObjectName(QString::fromUtf8("label_control_Pedal1"));
        label_control_Pedal1->setGeometry(QRect(10, 30, 81, 21));
        control_Pedal1 = new QComboBox(gb_Control);
        control_Pedal1->setObjectName(QString::fromUtf8("control_Pedal1"));
        control_Pedal1->setGeometry(QRect(100, 30, 141, 25));
        label_control_Pedal2 = new QLabel(gb_Control);
        label_control_Pedal2->setObjectName(QString::fromUtf8("label_control_Pedal2"));
        label_control_Pedal2->setGeometry(QRect(10, 60, 81, 21));
        control_Pedal2 = new QComboBox(gb_Control);
        control_Pedal2->setObjectName(QString::fromUtf8("control_Pedal2"));
        control_Pedal2->setGeometry(QRect(100, 60, 141, 25));
        control_Pedal3 = new QComboBox(gb_Control);
        control_Pedal3->setObjectName(QString::fromUtf8("control_Pedal3"));
        control_Pedal3->setGeometry(QRect(100, 90, 141, 25));
        label_control_Pedal3 = new QLabel(gb_Control);
        label_control_Pedal3->setObjectName(QString::fromUtf8("label_control_Pedal3"));
        label_control_Pedal3->setGeometry(QRect(10, 90, 81, 21));
        label_control_Control1 = new QLabel(gb_Control);
        label_control_Control1->setObjectName(QString::fromUtf8("label_control_Control1"));
        label_control_Control1->setGeometry(QRect(10, 120, 81, 21));
        control_Control1 = new QComboBox(gb_Control);
        control_Control1->setObjectName(QString::fromUtf8("control_Control1"));
        control_Control1->setGeometry(QRect(100, 120, 141, 25));
        label_control_Control2 = new QLabel(gb_Control);
        label_control_Control2->setObjectName(QString::fromUtf8("label_control_Control2"));
        label_control_Control2->setGeometry(QRect(10, 150, 81, 21));
        control_Control2 = new QComboBox(gb_Control);
        control_Control2->setObjectName(QString::fromUtf8("control_Control2"));
        control_Control2->setGeometry(QRect(100, 150, 141, 25));
        label_control_Expression = new QLabel(gb_Control);
        label_control_Expression->setObjectName(QString::fromUtf8("label_control_Expression"));
        label_control_Expression->setGeometry(QRect(10, 180, 81, 21));
        control_Expression = new QComboBox(gb_Control);
        control_Expression->setObjectName(QString::fromUtf8("control_Expression"));
        control_Expression->setGeometry(QRect(100, 180, 141, 25));
        toolButton = new QToolButton(BossRc500MainDialog);
        toolButton->setObjectName(QString::fromUtf8("toolButton"));
        toolButton->setGeometry(QRect(10, 50, 111, 24));
        toolButton->setPopupMode(QToolButton::InstantPopup);
        QWidget::setTabOrder(cb_Memory, button_Edit);
        QWidget::setTabOrder(button_Edit, cb_CopyFrom);
        QWidget::setTabOrder(cb_CopyFrom, cb_CopyTo);
        QWidget::setTabOrder(cb_CopyTo, button_Copy);
        QWidget::setTabOrder(button_Copy, track1_Level);
        QWidget::setTabOrder(track1_Level, track1_Reverse);
        QWidget::setTabOrder(track1_Reverse, track1_LoopFx);
        QWidget::setTabOrder(track1_LoopFx, track1_OneShot);
        QWidget::setTabOrder(track1_OneShot, track1_Pan);
        QWidget::setTabOrder(track1_Pan, track1_Start);
        QWidget::setTabOrder(track1_Start, track1_Stop);
        QWidget::setTabOrder(track1_Stop, track1_Measure);
        QWidget::setTabOrder(track1_Measure, track1_LoopSync);
        QWidget::setTabOrder(track1_LoopSync, track1_TempoSync);
        QWidget::setTabOrder(track1_TempoSync, track1_Input);
        QWidget::setTabOrder(track1_Input, track1_Output);
        QWidget::setTabOrder(track1_Output, track2_Level);
        QWidget::setTabOrder(track2_Level, track2_Reverse);
        QWidget::setTabOrder(track2_Reverse, track2_LoopFx);
        QWidget::setTabOrder(track2_LoopFx, track2_OneShot);
        QWidget::setTabOrder(track2_OneShot, track2_Pan);
        QWidget::setTabOrder(track2_Pan, track2_Start);
        QWidget::setTabOrder(track2_Start, track2_Stop);
        QWidget::setTabOrder(track2_Stop, track2_Measure);
        QWidget::setTabOrder(track2_Measure, track2_LoopSync);
        QWidget::setTabOrder(track2_LoopSync, track2_TempoSync);
        QWidget::setTabOrder(track2_TempoSync, track2_Input);
        QWidget::setTabOrder(track2_Input, track2_Output);
        QWidget::setTabOrder(track2_Output, rhythm_Level);
        QWidget::setTabOrder(rhythm_Level, rhythm_Reverb);
        QWidget::setTabOrder(rhythm_Reverb, rhythm_Pattern);
        QWidget::setTabOrder(rhythm_Pattern, rhythm_Variation);
        QWidget::setTabOrder(rhythm_Variation, rhythm_VarChange);
        QWidget::setTabOrder(rhythm_VarChange, rhythm_Kit);
        QWidget::setTabOrder(rhythm_Kit, rhythm_Beat);
        QWidget::setTabOrder(rhythm_Beat, rhythm_Start);
        QWidget::setTabOrder(rhythm_Start, rhythm_Stop);
        QWidget::setTabOrder(rhythm_Stop, rhythm_RecCount);
        QWidget::setTabOrder(rhythm_RecCount, rhythm_PlayCount);
        QWidget::setTabOrder(rhythm_PlayCount, rhythm_Fill);
        QWidget::setTabOrder(rhythm_Fill, rhythm_Part1);
        QWidget::setTabOrder(rhythm_Part1, rhythm_Part2);
        QWidget::setTabOrder(rhythm_Part2, rhythm_Part3);
        QWidget::setTabOrder(rhythm_Part3, rhythm_Part4);
        QWidget::setTabOrder(rhythm_Part4, rhythm_ToneLow);
        QWidget::setTabOrder(rhythm_ToneLow, rhythm_ToneHigh);
        QWidget::setTabOrder(rhythm_ToneHigh, record_DubMode);
        QWidget::setTabOrder(record_DubMode, record_RecordAction);
        QWidget::setTabOrder(record_RecordAction, record_Quantize);
        QWidget::setTabOrder(record_Quantize, record_AutoRecord);
        QWidget::setTabOrder(record_AutoRecord, record_AutoRecordSensitivity);
        QWidget::setTabOrder(record_AutoRecordSensitivity, record_AutoRecordSource);
        QWidget::setTabOrder(record_AutoRecordSource, record_LoopLength);
        QWidget::setTabOrder(record_LoopLength, play_Tempo);
        QWidget::setTabOrder(play_Tempo, play_PlayMode);
        QWidget::setTabOrder(play_PlayMode, play_SingleChange);
        QWidget::setTabOrder(play_SingleChange, play_Level);
        QWidget::setTabOrder(play_Level, play_FadeTime);
        QWidget::setTabOrder(play_FadeTime, play_AllStart);
        QWidget::setTabOrder(play_AllStart, play_TrackChain);
        QWidget::setTabOrder(play_TrackChain, loopFx_Sw);
        QWidget::setTabOrder(loopFx_Sw, loopFx_Type);
        QWidget::setTabOrder(loopFx_Type, loopFx_ScatLen);
        QWidget::setTabOrder(loopFx_ScatLen, loopFx_ReptLen);
        QWidget::setTabOrder(loopFx_ReptLen, loopFx_Shift);
        QWidget::setTabOrder(loopFx_Shift, loopFx_Flick);

        retranslateUi(BossRc500MainDialog);

        QMetaObject::connectSlotsByName(BossRc500MainDialog);
    } // setupUi

    void retranslateUi(QDialog *BossRc500MainDialog)
    {
        BossRc500MainDialog->setWindowTitle(QCoreApplication::translate("BossRc500MainDialog", "Dialog", nullptr));
        label_LoopStation->setText(QString());
        label_To->setText(QCoreApplication::translate("BossRc500MainDialog", "To", nullptr));
        label_Memory->setText(QCoreApplication::translate("BossRc500MainDialog", "Memory", nullptr));
        label_CopyTo->setText(QCoreApplication::translate("BossRc500MainDialog", "From", nullptr));
        label_Boss->setText(QString());
        gp_Track1->setTitle(QCoreApplication::translate("BossRc500MainDialog", "TRACK 1", nullptr));
        track1_Reverse->setText(QCoreApplication::translate("BossRc500MainDialog", "Reverse", nullptr));
        label_track1_Level->setText(QCoreApplication::translate("BossRc500MainDialog", "Level", nullptr));
        track1_LoopFx->setText(QCoreApplication::translate("BossRc500MainDialog", "Loop Fx", nullptr));
        track1_OneShot->setText(QCoreApplication::translate("BossRc500MainDialog", "One Shot", nullptr));
        label_track1_Pan->setText(QCoreApplication::translate("BossRc500MainDialog", "Pan", nullptr));
        label_track1_Stop->setText(QCoreApplication::translate("BossRc500MainDialog", "Stop", nullptr));
        label_track1_Start->setText(QCoreApplication::translate("BossRc500MainDialog", "Start", nullptr));
        label_track1_Measure->setText(QCoreApplication::translate("BossRc500MainDialog", "Measure", nullptr));
        track1_LoopSync->setText(QCoreApplication::translate("BossRc500MainDialog", "Loop Sync", nullptr));
        track1_TempoSync->setText(QCoreApplication::translate("BossRc500MainDialog", "Tempo  Sync", nullptr));
        label_track1_Output->setText(QCoreApplication::translate("BossRc500MainDialog", "Output", nullptr));
        label_track1_Input->setText(QCoreApplication::translate("BossRc500MainDialog", "Input", nullptr));
        label_track1_PlyLevel->setText(QCoreApplication::translate("BossRc500MainDialog", "0", nullptr));
        gp_Track2->setTitle(QCoreApplication::translate("BossRc500MainDialog", "TRACK 2", nullptr));
        label_track2_Stop->setText(QCoreApplication::translate("BossRc500MainDialog", "Stop", nullptr));
        label_track2_Output->setText(QCoreApplication::translate("BossRc500MainDialog", "Output", nullptr));
        track2_OneShot->setText(QCoreApplication::translate("BossRc500MainDialog", "One Shot", nullptr));
        track2_TempoSync->setText(QCoreApplication::translate("BossRc500MainDialog", "Tempo  Sync", nullptr));
        track2_LoopSync->setText(QCoreApplication::translate("BossRc500MainDialog", "Loop Sync", nullptr));
        label_track2_Measure->setText(QCoreApplication::translate("BossRc500MainDialog", "Measure", nullptr));
        label_track2_Start->setText(QCoreApplication::translate("BossRc500MainDialog", "Start", nullptr));
        label_track2_Input->setText(QCoreApplication::translate("BossRc500MainDialog", "Input", nullptr));
        track2_Reverse->setText(QCoreApplication::translate("BossRc500MainDialog", "Reverse", nullptr));
        track2_LoopFx->setText(QCoreApplication::translate("BossRc500MainDialog", "Loop Fx", nullptr));
        label_track2_Level->setText(QCoreApplication::translate("BossRc500MainDialog", "Level", nullptr));
        label_track2_Pan->setText(QCoreApplication::translate("BossRc500MainDialog", "Pan", nullptr));
        label_track2_PlyLevel->setText(QCoreApplication::translate("BossRc500MainDialog", "0", nullptr));
        button_Copy->setText(QCoreApplication::translate("BossRc500MainDialog", "Copy", nullptr));
        gp_Record->setTitle(QCoreApplication::translate("BossRc500MainDialog", "RECORD", nullptr));
        label_record_DubMode->setText(QCoreApplication::translate("BossRc500MainDialog", "Dub Mode", nullptr));
        label_record_Quantize->setText(QCoreApplication::translate("BossRc500MainDialog", "Quantize", nullptr));
        label_record_RecordAction->setText(QCoreApplication::translate("BossRc500MainDialog", "Record Action", nullptr));
        record_AutoRecord->setText(QCoreApplication::translate("BossRc500MainDialog", "Auto Record", nullptr));
        label_record_AutoRecordSource->setText(QCoreApplication::translate("BossRc500MainDialog", "Auto Record Source", nullptr));
        label_record_Input_3->setText(QCoreApplication::translate("BossRc500MainDialog", "Auto Rec. Sensitivity", nullptr));
        label_record_LoopLength->setText(QCoreApplication::translate("BossRc500MainDialog", "Loop Length", nullptr));
        gp_Play->setTitle(QCoreApplication::translate("BossRc500MainDialog", "PLAY", nullptr));
        label_play_PlayMode->setText(QCoreApplication::translate("BossRc500MainDialog", "Play Mode", nullptr));
        label_play_Level->setText(QCoreApplication::translate("BossRc500MainDialog", "Level", nullptr));
        label_play_SingleChange->setText(QCoreApplication::translate("BossRc500MainDialog", "Single Change", nullptr));
        label_play_AllStart->setText(QCoreApplication::translate("BossRc500MainDialog", "All Start", nullptr));
        label_play_FadeTime->setText(QCoreApplication::translate("BossRc500MainDialog", "Fade Time", nullptr));
        label_play_TrackChain->setText(QCoreApplication::translate("BossRc500MainDialog", "Track Chain", nullptr));
        label_play_Tempo->setText(QCoreApplication::translate("BossRc500MainDialog", "Tempo", nullptr));
        gp_Rhythm->setTitle(QCoreApplication::translate("BossRc500MainDialog", "RHYTHM", nullptr));
        label_rhythm_Level->setText(QCoreApplication::translate("BossRc500MainDialog", "Level", nullptr));
        label_rhythm_Reverb->setText(QCoreApplication::translate("BossRc500MainDialog", "Reverb", nullptr));
        label_rhythm_Pattern->setText(QCoreApplication::translate("BossRc500MainDialog", "Pattern", nullptr));
        label_rhythm_Variation->setText(QCoreApplication::translate("BossRc500MainDialog", "Variation", nullptr));
        label_rhythm_VarChange->setText(QCoreApplication::translate("BossRc500MainDialog", "Var. Change", nullptr));
        label_rhythm_Kit->setText(QCoreApplication::translate("BossRc500MainDialog", "Kit", nullptr));
        label_rhythm_Beat->setText(QCoreApplication::translate("BossRc500MainDialog", "Beat", nullptr));
        label_rhythm_Start->setText(QCoreApplication::translate("BossRc500MainDialog", "Start", nullptr));
        label_rhythm_Stop->setText(QCoreApplication::translate("BossRc500MainDialog", "Stop", nullptr));
        label_rhythm_RecCount->setText(QCoreApplication::translate("BossRc500MainDialog", "Rec Count", nullptr));
        label_rhythm_PlayCount->setText(QCoreApplication::translate("BossRc500MainDialog", "Play Count", nullptr));
        rhythm_Fill->setText(QCoreApplication::translate("BossRc500MainDialog", "Fill", nullptr));
        rhythm_Part1->setText(QCoreApplication::translate("BossRc500MainDialog", "1", nullptr));
        rhythm_Part2->setText(QCoreApplication::translate("BossRc500MainDialog", "2", nullptr));
        rhythm_Part3->setText(QCoreApplication::translate("BossRc500MainDialog", "3", nullptr));
        rhythm_Part4->setText(QCoreApplication::translate("BossRc500MainDialog", "4", nullptr));
        label_rhythm_Part->setText(QCoreApplication::translate("BossRc500MainDialog", "Part", nullptr));
        label_rhythm_Tone->setText(QCoreApplication::translate("BossRc500MainDialog", "Low Tone High", nullptr));
        gb_LoopFx->setTitle(QCoreApplication::translate("BossRc500MainDialog", "LOOP FX", nullptr));
        label_loopFx_Type->setText(QCoreApplication::translate("BossRc500MainDialog", "Type", nullptr));
        label_loopFx_ScatLen->setText(QCoreApplication::translate("BossRc500MainDialog", "Scat Len", nullptr));
        label_loopFx_ReptLen->setText(QCoreApplication::translate("BossRc500MainDialog", "Rept Len", nullptr));
        label_loopFx_Shift->setText(QCoreApplication::translate("BossRc500MainDialog", "Shift", nullptr));
        label_loopFx_Flick->setText(QCoreApplication::translate("BossRc500MainDialog", "Flick", nullptr));
        loopFx_Sw->setText(QCoreApplication::translate("BossRc500MainDialog", "Loop Fx", nullptr));
        button_Edit->setText(QCoreApplication::translate("BossRc500MainDialog", "Edit", nullptr));
        gb_Control->setTitle(QCoreApplication::translate("BossRc500MainDialog", "CONTROL", nullptr));
        label_control_Pedal1->setText(QCoreApplication::translate("BossRc500MainDialog", "Pedal 1", nullptr));
        label_control_Pedal2->setText(QCoreApplication::translate("BossRc500MainDialog", "Pedal 2", nullptr));
        label_control_Pedal3->setText(QCoreApplication::translate("BossRc500MainDialog", "Pedal 3", nullptr));
        label_control_Control1->setText(QCoreApplication::translate("BossRc500MainDialog", "Control 1", nullptr));
        label_control_Control2->setText(QCoreApplication::translate("BossRc500MainDialog", "Control 2", nullptr));
        label_control_Expression->setText(QCoreApplication::translate("BossRc500MainDialog", "Expression", nullptr));
        toolButton->setText(QCoreApplication::translate("BossRc500MainDialog", "Menu", nullptr));
    } // retranslateUi

};

QT_END_NAMESPACE

#endif // BOSS_2D_RC500YWKPPY_H
